/**
 * @method   setPageColor
 * @summary  Determines the dynamic CSS classes for the page background based on Quasar's dark mode state and screen responsiveness.
 *
 * @author   Avinash Sahoo
 * @created  19-12-2025
 */
function setPageColor() {
   let self = this;
   try {
      return [self.$q.dark.isActive ? '' : 'bg-white', self.$q.screen.lt.md ? 'main-page-medium-screen' : ''];
   }
   catch (error) {
      return ''
   }
}

/**
 * @method   setDbNumberTrackColor
 * @summary  Determines the dynamic Colour for the track of the DB Number Chart based on Quasar's dark mode state.
 *
 * @author   Avinash Sahoo
 * @created  19-12-2025
 */
function setDbNumberTrackColor() {
   let self = this;
   try {
      return self.$q.dark.isActive ? '#37474f' : '#f2f2f2';
   }
   catch (error) {
      return ''
   }
}

/**
 * @method   setDbNumberClass
 * @summary  Determines the dynamic CSS classes for the DB Number Chart based on Quasar's dark mode state.
 *
 * @author   Avinash Sahoo
 * @created  19-12-2025
 */
function setDbNumberClass() {
   let self = this;
   try {
      return self.$q.dark.isActive ? 'db-number-chart-dark' : 'db-number-chart-light';
   }
   catch (error) {
      return ''
   }
}

/**
 * @method   setChartContainerClass
 * @summary  Determines the dynamic classes for the Chart Container based on screen responsiveness.
 *
 * @author   Avinash Sahoo
 * @created  19-12-2025
 */
function setChartContainerClass() {
   let self = this;
   try {
      return self.$q.screen.lt.md ? 'col-12' : 'col-6';
   }
   catch (error) {
      return ''
   }
}

/**
 * @method   setHeaderTitleColor
 * @summary  Determines the dynamic CSS classes for the Header Title based on Quasar's dark mode state.
 *
 * @author   Avinash Sahoo
 * @created  22-12-2025
 */
function setHeaderTitleColor() {
   let self = this;
   try {
      return self.$q.dark.isActive ? 'header-title-dark' : 'header-title-light';
   }
   catch (error) {
      return ''
   }
}

export const substationPages = [
  { label: 'Hcm Lane No.3 New (33/11KV)', value: 'ess-hcm-lane-no-3-new-33-11kv', route: '/crew-management', keywords: ["hcm", "lane", "3", "new", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'National Archieves (33/11KV)', value: 'ess-national-archieves-33-11kv', route: '/crew-management', keywords: ["national", "archieves", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Raisina Road (33/11KV)', value: 'ess-raisina-road-33-11kv', route: '/crew-management', keywords: ["raisina", "road", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Tilak Lane (33/11KV)', value: 'ess-tilak-lane-33-11kv', route: '/crew-management', keywords: ["tilak", "lane", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Mandi House (33/11KV)', value: 'ess-mandi-house-33-11kv', route: '/crew-management', keywords: ["mandi", "house", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Raja Bazar (33/11KV)', value: 'ess-raja-bazar-33-11kv', route: '/crew-management', keywords: ["raja", "bazar", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Baird Lane (33/11KV)', value: 'ess-baird-lane-33-11kv', route: '/crew-management', keywords: ["baird", "lane", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Hanuman Road New (33/11KV)', value: 'ess-hanuman-road-new-33-11kv', route: '/crew-management', keywords: ["hanuman", "road", "new", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'B.D. Marg (33/11KV) & (66/11KV)', value: 'ess-b-d-marg-33-11kv-66-11kv', route: '/crew-management', keywords: ["b", "d", "marg", "33", "11kv", "66", "ess", "substation", "66kv", "33kv"] },
  { label: 'Delhi Police Headquaters 33/11KV', value: 'ess-delhi-police-headquaters-33-11kv', route: '/crew-management', keywords: ["delhi", "police", "headquaters", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'School Lane (33/11KV) & (66/33/11KV)', value: 'ess-school-lane-33-11kv-66-33-11kv', route: '/crew-management', keywords: ["school", "lane", "33", "11kv", "66", "ess", "substation", "66kv", "33kv"] },
  { label: 'Scindia House (33/11KV)', value: 'ess-scindia-house-33-11kv', route: '/crew-management', keywords: ["scindia", "house", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Connaught Place (33/11KV) New', value: 'ess-connaught-place-33-11kv-new', route: '/crew-management', keywords: ["connaught", "place", "33", "11kv", "new", "ess", "substation", "66kv", "33kv"] },
  { label: 'Dalhousie Road 33/11KV', value: 'ess-dalhousie-road-33-11kv', route: '/crew-management', keywords: ["dalhousie", "road", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Shahjahan Road No 7 (33/11KV)', value: 'ess-shahjahan-road-no-7-33-11kv', route: '/crew-management', keywords: ["shahjahan", "road", "7", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Nirman Bhawan (33/11KV)', value: 'ess-nirman-bhawan-33-11kv', route: '/crew-management', keywords: ["nirman", "bhawan", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Rajiv Gandhi Bhawan (33/11KV)', value: 'ess-rajiv-gandhi-bhawan-33-11kv', route: '/crew-management', keywords: ["rajiv", "gandhi", "bhawan", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Jorbagh Aliganj (33/11KV)', value: 'ess-jorbagh-aliganj-33-11kv', route: '/crew-management', keywords: ["jorbagh", "aliganj", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Vidyut Bhawan (33/11KV) Old + New & (66/33KV)', value: 'ess-vidyut-bhawan-33-11kv-old-new-66-33kv', route: '/crew-management', keywords: ["vidyut", "bhawan", "33", "11kv", "old", "new", "66", "33kv", "ess", "substation", "66kv"] },
  { label: 'Race Course New (33/11KV)', value: 'ess-race-course-new-33-11kv', route: '/crew-management', keywords: ["race", "course", "new", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Bapu Dham (33/11KV) Old + New & (66/33KV)', value: 'ess-bapu-dham-33-11kv-old-new-66-33kv', route: '/crew-management', keywords: ["bapu", "dham", "33", "11kv", "old", "new", "66", "33kv", "ess", "substation", "66kv"] },
  { label: 'State Guest House (33/11KV) & (66/11KV)', value: 'ess-state-guest-house-33-11kv-66-11kv', route: '/crew-management', keywords: ["state", "guest", "house", "33", "11kv", "66", "ess", "substation", "66kv", "33kv"] },
  { label: 'ESS-1 East Kidwai Nagar 33/11KV', value: 'ess-ess-1-east-kidwai-nagar-33-11kv', route: '/crew-management', keywords: ["ess", "1", "east", "kidwai", "nagar", "33", "11kv", "substation", "66kv", "33kv"] },
  { label: 'ESS-2 East Kidwai Nagar 33/11KV', value: 'ess-ess-2-east-kidwai-nagar-33-11kv', route: '/crew-management', keywords: ["ess", "2", "east", "kidwai", "nagar", "33", "11kv", "substation", "66kv", "33kv"] },
  { label: 'Aiims (33/11KV)', value: 'ess-aiims-33-11kv', route: '/crew-management', keywords: ["aiims", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Keventer Dairy (33/11KV)', value: 'ess-keventer-dairy-33-11kv', route: '/crew-management', keywords: ["keventer", "dairy", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Sanjay Camp (33/11KV)', value: 'ess-sanjay-camp-33-11kv', route: '/crew-management', keywords: ["sanjay", "camp", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Nehru Park (33/11KV)', value: 'ess-nehru-park-33-11kv', route: '/crew-management', keywords: ["nehru", "park", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'ESS Netaji Nagar (33/11KV)', value: 'ess-ess-netaji-nagar-33-11kv', route: '/crew-management', keywords: ["ess", "netaji", "nagar", "33", "11kv", "substation", "66kv", "33kv"] },
  { label: 'Trauma Centre (33/11KV)', value: 'ess-trauma-centre-33-11kv', route: '/crew-management', keywords: ["trauma", "centre", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Kidwai Nagar West (33/11KV)', value: 'ess-kidwai-nagar-west-33-11kv', route: '/crew-management', keywords: ["kidwai", "nagar", "west", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: 'Aiims New (33/11KV)', value: 'ess-aiims-new-33-11kv', route: '/crew-management', keywords: ["aiims", "new", "33", "11kv", "ess", "substation", "66kv", "33kv"] },
  { label: '2 Aurangzeb Road', value: '11kvess-2-aurangzeb-road', route: '/crew-management', keywords: ["2", "aurangzeb", "road", "11kvess", "substation", "11kv"] },
  { label: '6 Aurangzeb Road', value: '11kvess-6-aurangzeb-road', route: '/crew-management', keywords: ["6", "aurangzeb", "road", "11kvess", "substation", "11kv"] },
  { label: 'Aakash mesh', value: '11kvess-aakash-mesh', route: '/crew-management', keywords: ["aakash", "mesh", "11kvess", "substation", "11kv"] },
  { label: 'Akbar Bhawan', value: '11kvess-akbar-bhawan', route: '/crew-management', keywords: ["akbar", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Aliganj No.2', value: '11kvess-aliganj-no-2', route: '/crew-management', keywords: ["aliganj", "2", "11kvess", "substation", "11kv"] },
  { label: 'American School', value: '11kvess-american-school', route: '/crew-management', keywords: ["american", "school", "11kvess", "substation", "11kv"] },
  { label: 'Assam House', value: '11kvess-assam-house', route: '/crew-management', keywords: ["assam", "house", "11kvess", "substation", "11kv"] },
  { label: 'Booster Pump Sarojini Nagar', value: '11kvess-booster-pump-sarojini-nagar', route: '/crew-management', keywords: ["booster", "pump", "sarojini", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'Children Park', value: '11kvess-children-park', route: '/crew-management', keywords: ["children", "park", "11kvess", "substation", "11kv"] },
  { label: 'CRSD Hanger', value: '11kvess-crsd-hanger', route: '/crew-management', keywords: ["crsd", "hanger", "11kvess", "substation", "11kv"] },
  { label: 'Delhi High court \'C\' Block', value: '11kvess-delhi-high-court-c-block', route: '/crew-management', keywords: ["delhi", "high", "court", "c", "block", "11kvess", "substation", "11kv"] },
  { label: 'ESS No.7 (Shahjahan Road)', value: '11kvess-ess-no-7-shahjahan-road', route: '/crew-management', keywords: ["ess", "7", "shahjahan", "road", "11kvess", "substation", "11kv"] },
  { label: 'Factory Road', value: '11kvess-factory-road', route: '/crew-management', keywords: ["factory", "road", "11kvess", "substation", "11kv"] },
  { label: 'IGMT', value: '11kvess-igmt', route: '/crew-management', keywords: ["igmt", "11kvess", "substation", "11kv"] },
  { label: 'Indira Niketan', value: '11kvess-indira-niketan', route: '/crew-management', keywords: ["indira", "niketan", "11kvess", "substation", "11kv"] },
  { label: 'J&K House', value: '11kvess-j-k-house', route: '/crew-management', keywords: ["j", "k", "house", "11kvess", "substation", "11kv"] },
  { label: 'Japan embassy New', value: '11kvess-japan-embassy-new', route: '/crew-management', keywords: ["japan", "embassy", "new", "11kvess", "substation", "11kv"] },
  { label: 'Jorbagh no.3', value: '11kvess-jorbagh-no-3', route: '/crew-management', keywords: ["jorbagh", "3", "11kvess", "substation", "11kv"] },
  { label: 'Kaka Nagar', value: '11kvess-kaka-nagar', route: '/crew-management', keywords: ["kaka", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'Kidwai Ngar East No.1 3311KV', value: '11kvess-kidwai-ngar-east-no-1-3311kv', route: '/crew-management', keywords: ["kidwai", "ngar", "east", "1", "3311kv", "11kvess", "substation", "11kv"] },
  { label: 'Laxmi Bai Nagar No.II', value: '11kvess-laxmi-bai-nagar-no-ii', route: '/crew-management', keywords: ["laxmi", "bai", "nagar", "ii", "11kvess", "substation", "11kv"] },
  { label: 'Loundry Block', value: '11kvess-loundry-block', route: '/crew-management', keywords: ["loundry", "block", "11kvess", "substation", "11kv"] },
  { label: 'M.P Bhawan', value: '11kvess-m-p-bhawan', route: '/crew-management', keywords: ["m", "p", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.10', value: '11kvess-new-moti-bagh-no-10', route: '/crew-management', keywords: ["new", "moti", "bagh", "10", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.4', value: '11kvess-new-moti-bagh-no-4', route: '/crew-management', keywords: ["new", "moti", "bagh", "4", "11kvess", "substation", "11kv"] },
  { label: 'Railway Coloney-I', value: '11kvess-railway-coloney-i', route: '/crew-management', keywords: ["railway", "coloney", "i", "11kvess", "substation", "11kv"] },
  { label: 'S.J staff Qtr No.2', value: '11kvess-s-j-staff-qtr-no-2', route: '/crew-management', keywords: ["s", "j", "staff", "qtr", "2", "11kvess", "substation", "11kv"] },
  { label: 'S.P Marg', value: '11kvess-s-p-marg', route: '/crew-management', keywords: ["s", "p", "marg", "11kvess", "substation", "11kv"] },
  { label: 'Samrat Hotel', value: '11kvess-samrat-hotel', route: '/crew-management', keywords: ["samrat", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'Singapur Embassey', value: '11kvess-singapur-embassey', route: '/crew-management', keywords: ["singapur", "embassey", "11kvess", "substation", "11kv"] },
  { label: 'UNESCO', value: '11kvess-unesco', route: '/crew-management', keywords: ["unesco", "11kvess", "substation", "11kv"] },
  { label: 'USSR Trade Building', value: '11kvess-ussr-trade-building', route: '/crew-management', keywords: ["ussr", "trade", "building", "11kvess", "substation", "11kv"] },
  { label: '10 Janpath', value: '11kvess-10-janpath', route: '/crew-management', keywords: ["10", "janpath", "11kvess", "substation", "11kv"] },
  { label: '10 P.RRoad', value: '11kvess-10-p-rroad', route: '/crew-management', keywords: ["10", "p", "rroad", "11kvess", "substation", "11kv"] },
  { label: '10- P.RRoad', value: '11kvess-10-p-rroad', route: '/crew-management', keywords: ["10", "p", "rroad", "11kvess", "substation", "11kv"] },
  { label: '11-B Aurangzeb Lane', value: '11kvess-11-b-aurangzeb-lane', route: '/crew-management', keywords: ["11", "b", "aurangzeb", "lane", "11kvess", "substation", "11kv"] },
  { label: '16 Akbar Road', value: '11kvess-16-akbar-road', route: '/crew-management', keywords: ["16", "akbar", "road", "11kvess", "substation", "11kv"] },
  { label: '18 Akbar Road', value: '11kvess-18-akbar-road', route: '/crew-management', keywords: ["18", "akbar", "road", "11kvess", "substation", "11kv"] },
  { label: '23 P.R Road', value: '11kvess-23-p-r-road', route: '/crew-management', keywords: ["23", "p", "r", "road", "11kvess", "substation", "11kv"] },
  { label: '2-3 Panchsheel Marg', value: '11kvess-2-3-panchsheel-marg', route: '/crew-management', keywords: ["2", "3", "panchsheel", "marg", "11kvess", "substation", "11kv"] },
  { label: '3, 4 South End Lane', value: '11kvess-3-4-south-end-lane', route: '/crew-management', keywords: ["3", "4", "south", "end", "lane", "11kvess", "substation", "11kv"] },
  { label: '30 January Lane', value: '11kvess-30-january-lane', route: '/crew-management', keywords: ["30", "january", "lane", "11kvess", "substation", "11kv"] },
  { label: '31-P.R Road', value: '11kvess-31-p-r-road', route: '/crew-management', keywords: ["31", "p", "r", "road", "11kvess", "substation", "11kv"] },
  { label: '32, Amrita Shergil Marg', value: '11kvess-32-amrita-shergil-marg', route: '/crew-management', keywords: ["32", "amrita", "shergil", "marg", "11kvess", "substation", "11kv"] },
  { label: '33/11KV Aliganj', value: '11kvess-33-11kv-aliganj', route: '/crew-management', keywords: ["33", "11kv", "aliganj", "11kvess", "substation"] },
  { label: '33/11KV Rajeev Gandhi Bhawan', value: '11kvess-33-11kv-rajeev-gandhi-bhawan', route: '/crew-management', keywords: ["33", "11kv", "rajeev", "gandhi", "bhawan", "11kvess", "substation"] },
  { label: '44, Amrita Shergil Marg', value: '11kvess-44-amrita-shergil-marg', route: '/crew-management', keywords: ["44", "amrita", "shergil", "marg", "11kvess", "substation", "11kv"] },
  { label: '5-Man Singh Road', value: '11kvess-5-man-singh-road', route: '/crew-management', keywords: ["5", "man", "singh", "road", "11kvess", "substation", "11kv"] },
  { label: '5-Block Lodhi Colony', value: '11kvess-5-block-lodhi-colony', route: '/crew-management', keywords: ["5", "block", "lodhi", "colony", "11kvess", "substation", "11kv"] },
  { label: '7 P.R Road', value: '11kvess-7-p-r-road', route: '/crew-management', keywords: ["7", "p", "r", "road", "11kvess", "substation", "11kv"] },
  { label: '9 P.R. Road', value: '11kvess-9-p-r-road', route: '/crew-management', keywords: ["9", "p", "r", "road", "11kvess", "substation", "11kv"] },
  { label: 'Afganistan Embassy', value: '11kvess-afganistan-embassy', route: '/crew-management', keywords: ["afganistan", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Afro-Asian', value: '11kvess-afro-asian', route: '/crew-management', keywords: ["afro", "asian", "11kvess", "substation", "11kv"] },
  { label: 'AIIMS', value: '11kvess-aiims', route: '/crew-management', keywords: ["aiims", "11kvess", "substation", "11kv"] },
  { label: 'Akbar Lane', value: '11kvess-akbar-lane', route: '/crew-management', keywords: ["akbar", "lane", "11kvess", "substation", "11kv"] },
  { label: 'Aliganj No.1', value: '11kvess-aliganj-no-1', route: '/crew-management', keywords: ["aliganj", "1", "11kvess", "substation", "11kv"] },
  { label: 'American Embassy', value: '11kvess-american-embassy', route: '/crew-management', keywords: ["american", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Anant Ram Dairy', value: '11kvess-anant-ram-dairy', route: '/crew-management', keywords: ["anant", "ram", "dairy", "11kvess", "substation", "11kv"] },
  { label: 'Andman & Nikobar', value: '11kvess-andman-nikobar', route: '/crew-management', keywords: ["andman", "nikobar", "11kvess", "substation", "11kv"] },
  { label: 'Animal House', value: '11kvess-animal-house', route: '/crew-management', keywords: ["animal", "house", "11kvess", "substation", "11kv"] },
  { label: 'Ansari Nagar(E)', value: '11kvess-ansari-nagar-e', route: '/crew-management', keywords: ["ansari", "nagar", "e", "11kvess", "substation", "11kv"] },
  { label: 'Ansari Nagar(W)', value: '11kvess-ansari-nagar-w', route: '/crew-management', keywords: ["ansari", "nagar", "w", "11kvess", "substation", "11kv"] },
  { label: 'Aradhana building', value: '11kvess-aradhana-building', route: '/crew-management', keywords: ["aradhana", "building", "11kvess", "substation", "11kv"] },
  { label: 'Ashoka Hotel', value: '11kvess-ashoka-hotel', route: '/crew-management', keywords: ["ashoka", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'Assam Bhawan', value: '11kvess-assam-bhawan', route: '/crew-management', keywords: ["assam", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Aurangzeb Lane', value: '11kvess-aurangzeb-lane', route: '/crew-management', keywords: ["aurangzeb", "lane", "11kvess", "substation", "11kv"] },
  { label: 'Aurobindo Marg', value: '11kvess-aurobindo-marg', route: '/crew-management', keywords: ["aurobindo", "marg", "11kvess", "substation", "11kv"] },
  { label: 'Australia Embassy', value: '11kvess-australia-embassy', route: '/crew-management', keywords: ["australia", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Austriya Embassy', value: '11kvess-austriya-embassy', route: '/crew-management', keywords: ["austriya", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'B-Block Sarojini Nagar', value: '11kvess-b-block-sarojini-nagar', route: '/crew-management', keywords: ["b", "block", "sarojini", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'B Block Udyog Bhawan', value: '11kvess-b-block-udyog-bhawan', route: '/crew-management', keywords: ["b", "block", "udyog", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Bangal Guest House', value: '11kvess-bangal-guest-house', route: '/crew-management', keywords: ["bangal", "guest", "house", "11kvess", "substation", "11kv"] },
  { label: 'Bapa Nagar', value: '11kvess-bapa-nagar', route: '/crew-management', keywords: ["bapa", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'Bapu Dham', value: '11kvess-bapu-dham', route: '/crew-management', keywords: ["bapu", "dham", "11kvess", "substation", "11kv"] },
  { label: 'Bapu Dham Complex', value: '11kvess-bapu-dham-complex', route: '/crew-management', keywords: ["bapu", "dham", "complex", "11kvess", "substation", "11kv"] },
  { label: 'Bardolai Marg', value: '11kvess-bardolai-marg', route: '/crew-management', keywords: ["bardolai", "marg", "11kvess", "substation", "11kv"] },
  { label: 'Belgium Embassy (Inside)', value: '11kvess-belgium-embassy-inside', route: '/crew-management', keywords: ["belgium", "embassy", "inside", "11kvess", "substation", "11kv"] },
  { label: 'Belgium Embassy Main', value: '11kvess-belgium-embassy-main', route: '/crew-management', keywords: ["belgium", "embassy", "main", "11kvess", "substation", "11kv"] },
  { label: 'Bharti Nagar', value: '11kvess-bharti-nagar', route: '/crew-management', keywords: ["bharti", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'Bhutan Embassy', value: '11kvess-bhutan-embassy', route: '/crew-management', keywords: ["bhutan", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Bihar Niwas', value: '11kvess-bihar-niwas', route: '/crew-management', keywords: ["bihar", "niwas", "11kvess", "substation", "11kv"] },
  { label: 'Bio-Tech', value: '11kvess-bio-tech', route: '/crew-management', keywords: ["bio", "tech", "11kvess", "substation", "11kv"] },
  { label: 'Blind Relief', value: '11kvess-blind-relief', route: '/crew-management', keywords: ["blind", "relief", "11kvess", "substation", "11kv"] },
  { label: 'British School', value: '11kvess-british-school', route: '/crew-management', keywords: ["british", "school", "11kvess", "substation", "11kv"] },
  { label: 'Buddha Jayanti Park', value: '11kvess-buddha-jayanti-park', route: '/crew-management', keywords: ["buddha", "jayanti", "park", "11kvess", "substation", "11kv"] },
  { label: 'Buddha Jayanti Pump', value: '11kvess-buddha-jayanti-pump', route: '/crew-management', keywords: ["buddha", "jayanti", "pump", "11kvess", "substation", "11kv"] },
  { label: 'Bulgariya Embassy', value: '11kvess-bulgariya-embassy', route: '/crew-management', keywords: ["bulgariya", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Burn & Plastic ward', value: '11kvess-burn-plastic-ward', route: '/crew-management', keywords: ["burn", "plastic", "ward", "11kvess", "substation", "11kv"] },
  { label: 'C.N center (AIIMS)', value: '11kvess-c-n-center-aiims', route: '/crew-management', keywords: ["c", "n", "center", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'Cancer Block', value: '11kvess-cancer-block', route: '/crew-management', keywords: ["cancer", "block", "11kvess", "substation", "11kv"] },
  { label: 'C-Block Sarojini Nagar', value: '11kvess-c-block-sarojini-nagar', route: '/crew-management', keywords: ["c", "block", "sarojini", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'CGHS Wellness Center Sector-13', value: '11kvess-cghs-wellness-center-sector-13', route: '/crew-management', keywords: ["cghs", "wellness", "center", "sector", "13", "11kvess", "substation", "11kv"] },
  { label: 'Chanakya Bhawan', value: '11kvess-chanakya-bhawan', route: '/crew-management', keywords: ["chanakya", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Chanakya Puri', value: '11kvess-chanakya-puri', route: '/crew-management', keywords: ["chanakya", "puri", "11kvess", "substation", "11kv"] },
  { label: 'Chandergupt Marg, Chanakya Puri', value: '11kvess-chandergupt-marg-chanakya-puri', route: '/crew-management', keywords: ["chandergupt", "marg", "chanakya", "puri", "11kvess", "substation", "11kv"] },
  { label: 'Chattishgarh Bhawan', value: '11kvess-chattishgarh-bhawan', route: '/crew-management', keywords: ["chattishgarh", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'C-II Moti Bagh', value: '11kvess-c-ii-moti-bagh', route: '/crew-management', keywords: ["c", "ii", "moti", "bagh", "11kvess", "substation", "11kv"] },
  { label: 'Circular Road', value: '11kvess-circular-road', route: '/crew-management', keywords: ["circular", "road", "11kvess", "substation", "11kv"] },
  { label: 'Claridges Hotel', value: '11kvess-claridges-hotel', route: '/crew-management', keywords: ["claridges", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'Convergent Center (New P.C. Teaching Block)', value: '11kvess-convergent-center-new-p-c-teaching-block', route: '/crew-management', keywords: ["convergent", "center", "new", "p", "c", "teaching", "block", "11kvess", "substation", "11kv"] },
  { label: 'CPWD Aliganj', value: '11kvess-cpwd-aliganj', route: '/crew-management', keywords: ["cpwd", "aliganj", "11kvess", "substation", "11kv"] },
  { label: 'CPWD Bapu Dham', value: '11kvess-cpwd-bapu-dham', route: '/crew-management', keywords: ["cpwd", "bapu", "dham", "11kvess", "substation", "11kv"] },
  { label: 'CSOI', value: '11kvess-csoi', route: '/crew-management', keywords: ["csoi", "11kvess", "substation", "11kv"] },
  { label: 'Dalhousie Road', value: '11kvess-dalhousie-road', route: '/crew-management', keywords: ["dalhousie", "road", "11kvess", "substation", "11kv"] },
  { label: 'Danish Embassy', value: '11kvess-danish-embassy', route: '/crew-management', keywords: ["danish", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'D-Block Sarojini Nagar', value: '11kvess-d-block-sarojini-nagar', route: '/crew-management', keywords: ["d", "block", "sarojini", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'Delhi Earth Center', value: '11kvess-delhi-earth-center', route: '/crew-management', keywords: ["delhi", "earth", "center", "11kvess", "substation", "11kv"] },
  { label: 'Delhi High court (Temp.)', value: '11kvess-delhi-high-court-temp', route: '/crew-management', keywords: ["delhi", "high", "court", "temp", "11kvess", "substation", "11kv"] },
  { label: 'Delhi High court \'A\' Block', value: '11kvess-delhi-high-court-a-block', route: '/crew-management', keywords: ["delhi", "high", "court", "a", "block", "11kvess", "substation", "11kv"] },
  { label: 'Delhi High court.\'S\' Block', value: '11kvess-delhi-high-court-s-block', route: '/crew-management', keywords: ["delhi", "high", "court", "s", "block", "11kvess", "substation", "11kv"] },
  { label: 'Delhi Police Security Line', value: '11kvess-delhi-police-security-line', route: '/crew-management', keywords: ["delhi", "police", "security", "line", "11kvess", "substation", "11kv"] },
  { label: 'Delhi Police Security Line Bapu Dham', value: '11kvess-delhi-police-security-line-bapu-dham', route: '/crew-management', keywords: ["delhi", "police", "security", "line", "bapu", "dham", "11kvess", "substation", "11kv"] },
  { label: 'DG-Block Sarojini Nagar', value: '11kvess-dg-block-sarojini-nagar', route: '/crew-management', keywords: ["dg", "block", "sarojini", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'DGCA', value: '11kvess-dgca', route: '/crew-management', keywords: ["dgca", "11kvess", "substation", "11kv"] },
  { label: 'D-I Vinay Marg', value: '11kvess-d-i-vinay-marg', route: '/crew-management', keywords: ["d", "i", "vinay", "marg", "11kvess", "substation", "11kv"] },
  { label: 'D-II Pump House', value: '11kvess-d-ii-pump-house', route: '/crew-management', keywords: ["d", "ii", "pump", "house", "11kvess", "substation", "11kv"] },
  { label: 'Dilli Hatt (Food & Craft Bazar)', value: '11kvess-dilli-hatt-food-craft-bazar', route: '/crew-management', keywords: ["dilli", "hatt", "food", "craft", "bazar", "11kvess", "substation", "11kv"] },
  { label: 'DLF ChanakyaPuri', value: '11kvess-dlf-chanakyapuri', route: '/crew-management', keywords: ["dlf", "chanakyapuri", "11kvess", "substation", "11kv"] },
  { label: 'Egypt Embassy', value: '11kvess-egypt-embassy', route: '/crew-management', keywords: ["egypt", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'ESS Chinmaya Mission', value: '11kvess-ess-chinmaya-mission', route: '/crew-management', keywords: ["ess", "chinmaya", "mission", "11kvess", "substation", "11kv"] },
  { label: 'ESS Lodhi Garden', value: '11kvess-ess-lodhi-garden', route: '/crew-management', keywords: ["ess", "lodhi", "garden", "11kvess", "substation", "11kv"] },
  { label: 'ESS Lodhi Plaza', value: '11kvess-ess-lodhi-plaza', route: '/crew-management', keywords: ["ess", "lodhi", "plaza", "11kvess", "substation", "11kv"] },
  { label: 'Ethiopia Embassy', value: '11kvess-ethiopia-embassy', route: '/crew-management', keywords: ["ethiopia", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Finland Embassy', value: '11kvess-finland-embassy', route: '/crew-management', keywords: ["finland", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Fire Brigade', value: '11kvess-fire-brigade', route: '/crew-management', keywords: ["fire", "brigade", "11kvess", "substation", "11kv"] },
  { label: 'G Block', value: '11kvess-g-block', route: '/crew-management', keywords: ["g", "block", "11kvess", "substation", "11kv"] },
  { label: 'Ghanna High commision', value: '11kvess-ghanna-high-commision', route: '/crew-management', keywords: ["ghanna", "high", "commision", "11kvess", "substation", "11kv"] },
  { label: 'Golf Apartment', value: '11kvess-golf-apartment', route: '/crew-management', keywords: ["golf", "apartment", "11kvess", "substation", "11kv"] },
  { label: 'Golf Club', value: '11kvess-golf-club', route: '/crew-management', keywords: ["golf", "club", "11kvess", "substation", "11kv"] },
  { label: 'Golf Link No.1', value: '11kvess-golf-link-no-1', route: '/crew-management', keywords: ["golf", "link", "1", "11kvess", "substation", "11kv"] },
  { label: 'Golf Link No.2', value: '11kvess-golf-link-no-2', route: '/crew-management', keywords: ["golf", "link", "2", "11kvess", "substation", "11kv"] },
  { label: 'Golf Link No.3', value: '11kvess-golf-link-no-3', route: '/crew-management', keywords: ["golf", "link", "3", "11kvess", "substation", "11kv"] },
  { label: 'Gujrat Bhawan', value: '11kvess-gujrat-bhawan', route: '/crew-management', keywords: ["gujrat", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Gujrat Sadan', value: '11kvess-gujrat-sadan', route: '/crew-management', keywords: ["gujrat", "sadan", "11kvess", "substation", "11kv"] },
  { label: 'Gymkhana Club', value: '11kvess-gymkhana-club', route: '/crew-management', keywords: ["gymkhana", "club", "11kvess", "substation", "11kv"] },
  { label: 'H-Block Sarojini Nagar', value: '11kvess-h-block-sarojini-nagar', route: '/crew-management', keywords: ["h", "block", "sarojini", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'Himachal Sadan', value: '11kvess-himachal-sadan', route: '/crew-management', keywords: ["himachal", "sadan", "11kvess", "substation", "11kv"] },
  { label: 'Hungery embassy', value: '11kvess-hungery-embassy', route: '/crew-management', keywords: ["hungery", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'I.R.C.H. (AIIMS)', value: '11kvess-i-r-c-h-aiims', route: '/crew-management', keywords: ["i", "r", "c", "h", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'IAC', value: '11kvess-iac', route: '/crew-management', keywords: ["iac", "11kvess", "substation", "11kv"] },
  { label: 'I-Block Sarojini Nagar', value: '11kvess-i-block-sarojini-nagar', route: '/crew-management', keywords: ["i", "block", "sarojini", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'II C Annexe', value: '11kvess-ii-c-annexe', route: '/crew-management', keywords: ["ii", "c", "annexe", "11kvess", "substation", "11kv"] },
  { label: 'II CC', value: '11kvess-ii-cc', route: '/crew-management', keywords: ["ii", "cc", "11kvess", "substation", "11kv"] },
  { label: 'Intech Building', value: '11kvess-intech-building', route: '/crew-management', keywords: ["intech", "building", "11kvess", "substation", "11kv"] },
  { label: 'Italy Embassy', value: '11kvess-italy-embassy', route: '/crew-management', keywords: ["italy", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Japan Embassey in side', value: '11kvess-japan-embassey-in-side', route: '/crew-management', keywords: ["japan", "embassey", "in", "side", "11kvess", "substation", "11kv"] },
  { label: 'Jawahar Lal Nehru Bhawan', value: '11kvess-jawahar-lal-nehru-bhawan', route: '/crew-management', keywords: ["jawahar", "lal", "nehru", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Jor bagh no 1', value: '11kvess-jor-bagh-no-1', route: '/crew-management', keywords: ["jor", "bagh", "1", "11kvess", "substation", "11kv"] },
  { label: 'Jor bagh no.4', value: '11kvess-jor-bagh-no-4', route: '/crew-management', keywords: ["jor", "bagh", "4", "11kvess", "substation", "11kv"] },
  { label: 'Jor bagh no.2', value: '11kvess-jor-bagh-no-2', route: '/crew-management', keywords: ["jor", "bagh", "2", "11kvess", "substation", "11kv"] },
  { label: 'Jor Bagh Pump House', value: '11kvess-jor-bagh-pump-house', route: '/crew-management', keywords: ["jor", "bagh", "pump", "house", "11kvess", "substation", "11kv"] },
  { label: 'Kapurthala house', value: '11kvess-kapurthala-house', route: '/crew-management', keywords: ["kapurthala", "house", "11kvess", "substation", "11kv"] },
  { label: 'Karnataka Bhawan', value: '11kvess-karnataka-bhawan', route: '/crew-management', keywords: ["karnataka", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Kashmir House Old', value: '11kvess-kashmir-house-old', route: '/crew-management', keywords: ["kashmir", "house", "old", "11kvess", "substation", "11kv"] },
  { label: 'Katahak Kala Kendra', value: '11kvess-katahak-kala-kendra', route: '/crew-management', keywords: ["katahak", "kala", "kendra", "11kvess", "substation", "11kv"] },
  { label: 'Kaventer Dairy 33/11 KV', value: '11kvess-kaventer-dairy-33-11-kv', route: '/crew-management', keywords: ["kaventer", "dairy", "33", "11", "11kvess", "substation", "11kv"] },
  { label: 'Kaventer Dairy Old', value: '11kvess-kaventer-dairy-old', route: '/crew-management', keywords: ["kaventer", "dairy", "old", "11kvess", "substation", "11kv"] },
  { label: 'K-Block Sarojini Nagar', value: '11kvess-k-block-sarojini-nagar', route: '/crew-management', keywords: ["k", "block", "sarojini", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'Kidwai Nagar West', value: '11kvess-kidwai-nagar-west', route: '/crew-management', keywords: ["kidwai", "nagar", "west", "11kvess", "substation", "11kv"] },
  { label: 'Kidwai Nagar East No.233 11KV', value: '11kvess-kidwai-nagar-east-no-233-11kv', route: '/crew-management', keywords: ["kidwai", "nagar", "east", "233", "11kv", "11kvess", "substation"] },
  { label: 'Kota House', value: '11kvess-kota-house', route: '/crew-management', keywords: ["kota", "house", "11kvess", "substation", "11kv"] },
  { label: 'Krishna manon Lane', value: '11kvess-krishna-manon-lane', route: '/crew-management', keywords: ["krishna", "manon", "lane", "11kvess", "substation", "11kv"] },
  { label: 'Laxmi Bai Nagar No.I', value: '11kvess-laxmi-bai-nagar-no-i', route: '/crew-management', keywords: ["laxmi", "bai", "nagar", "i", "11kvess", "substation", "11kv"] },
  { label: 'Lodhi Estate', value: '11kvess-lodhi-estate', route: '/crew-management', keywords: ["lodhi", "estate", "11kvess", "substation", "11kv"] },
  { label: 'Lok Nayak Bhawan A, B & C Board Panel No.3 D&E-Board', value: '11kvess-lok-nayak-bhawan-a-b-c-board-panel-no-3-d-e-board', route: '/crew-management', keywords: ["lok", "nayak", "bhawan", "a", "b", "c", "board", "panel", "3", "d", "e", "11kvess", "substation", "11kv"] },
  { label: 'Maitreyi College', value: '11kvess-maitreyi-college', route: '/crew-management', keywords: ["maitreyi", "college", "11kvess", "substation", "11kv"] },
  { label: 'Malasiya Embassy', value: '11kvess-malasiya-embassy', route: '/crew-management', keywords: ["malasiya", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Manipur Guest House', value: '11kvess-manipur-guest-house', route: '/crew-management', keywords: ["manipur", "guest", "house", "11kvess", "substation", "11kv"] },
  { label: 'Mauritius Embassy', value: '11kvess-mauritius-embassy', route: '/crew-management', keywords: ["mauritius", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Mausam Bhawan (New)', value: '11kvess-mausam-bhawan-new', route: '/crew-management', keywords: ["mausam", "bhawan", "new", "11kvess", "substation", "11kv"] },
  { label: 'Mausam Bhawan (Old)', value: '11kvess-mausam-bhawan-old', route: '/crew-management', keywords: ["mausam", "bhawan", "old", "11kvess", "substation", "11kv"] },
  { label: 'MEA Chanakya Puri', value: '11kvess-mea-chanakya-puri', route: '/crew-management', keywords: ["mea", "chanakya", "puri", "11kvess", "substation", "11kv"] },
  { label: 'MES Flat', value: '11kvess-mes-flat', route: '/crew-management', keywords: ["mes", "flat", "11kvess", "substation", "11kv"] },
  { label: 'Mizoram House', value: '11kvess-mizoram-house', route: '/crew-management', keywords: ["mizoram", "house", "11kvess", "substation", "11kv"] },
  { label: 'MOD Office Africa Avenue', value: '11kvess-mod-office-africa-avenue', route: '/crew-management', keywords: ["mod", "office", "africa", "avenue", "11kvess", "substation", "11kv"] },
  { label: 'Moti Bagh West', value: '11kvess-moti-bagh-west', route: '/crew-management', keywords: ["moti", "bagh", "west", "11kvess", "substation", "11kv"] },
  { label: 'MTNL Telephone Exchange Chankiya Puri', value: '11kvess-mtnl-telephone-exchange-chankiya-puri', route: '/crew-management', keywords: ["mtnl", "telephone", "exchange", "chankiya", "puri", "11kvess", "substation", "11kv"] },
  { label: 'Naroji nagar(Temp.)', value: '11kvess-naroji-nagar-temp', route: '/crew-management', keywords: ["naroji", "nagar", "temp", "11kvess", "substation", "11kv"] },
  { label: 'National Medical Library (AIIMS)', value: '11kvess-national-medical-library-aiims', route: '/crew-management', keywords: ["national", "medical", "library", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'National Museum', value: '11kvess-national-museum', route: '/crew-management', keywords: ["national", "museum", "11kvess", "substation", "11kv"] },
  { label: 'NATIONAL WAR MEMORIAL', value: '11kvess-national-war-memorial', route: '/crew-management', keywords: ["national", "war", "memorial", "11kvess", "substation", "11kv"] },
  { label: 'Naval Qtr', value: '11kvess-naval-qtr', route: '/crew-management', keywords: ["naval", "qtr", "11kvess", "substation", "11kv"] },
  { label: 'NDC', value: '11kvess-ndc', route: '/crew-management', keywords: ["ndc", "11kvess", "substation", "11kv"] },
  { label: 'Nehru Memorial', value: '11kvess-nehru-memorial', route: '/crew-management', keywords: ["nehru", "memorial", "11kvess", "substation", "11kv"] },
  { label: 'Nehru Park', value: '11kvess-nehru-park', route: '/crew-management', keywords: ["nehru", "park", "11kvess", "substation", "11kv"] },
  { label: 'Nehru Taramandal', value: '11kvess-nehru-taramandal', route: '/crew-management', keywords: ["nehru", "taramandal", "11kvess", "substation", "11kv"] },
  { label: 'Netaji Nagar 33 11KV', value: '11kvess-netaji-nagar-33-11kv', route: '/crew-management', keywords: ["netaji", "nagar", "33", "11kv", "11kvess", "substation"] },
  { label: 'Netaji Nagar A- Block', value: '11kvess-netaji-nagar-a-block', route: '/crew-management', keywords: ["netaji", "nagar", "a", "block", "11kvess", "substation", "11kv"] },
  { label: 'Netaji Nagar Booster Pump', value: '11kvess-netaji-nagar-booster-pump', route: '/crew-management', keywords: ["netaji", "nagar", "booster", "pump", "11kvess", "substation", "11kv"] },
  { label: 'Netaji Nagar Old', value: '11kvess-netaji-nagar-old', route: '/crew-management', keywords: ["netaji", "nagar", "old", "11kvess", "substation", "11kv"] },
  { label: 'New Emergency Block-Safdarjung Hospital', value: '11kvess-new-emergency-block-safdarjung-hospital', route: '/crew-management', keywords: ["new", "emergency", "block", "safdarjung", "hospital", "11kvess", "substation", "11kv"] },
  { label: 'New Malcha Marg', value: '11kvess-new-malcha-marg', route: '/crew-management', keywords: ["new", "malcha", "marg", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.11', value: '11kvess-new-moti-bagh-no-11', route: '/crew-management', keywords: ["new", "moti", "bagh", "11", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.2', value: '11kvess-new-moti-bagh-no-2', route: '/crew-management', keywords: ["new", "moti", "bagh", "2", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.3', value: '11kvess-new-moti-bagh-no-3', route: '/crew-management', keywords: ["new", "moti", "bagh", "3", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.5', value: '11kvess-new-moti-bagh-no-5', route: '/crew-management', keywords: ["new", "moti", "bagh", "5", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.6', value: '11kvess-new-moti-bagh-no-6', route: '/crew-management', keywords: ["new", "moti", "bagh", "6", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.7', value: '11kvess-new-moti-bagh-no-7', route: '/crew-management', keywords: ["new", "moti", "bagh", "7", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.8', value: '11kvess-new-moti-bagh-no-8', route: '/crew-management', keywords: ["new", "moti", "bagh", "8", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.9', value: '11kvess-new-moti-bagh-no-9', route: '/crew-management', keywords: ["new", "moti", "bagh", "9", "11kvess", "substation", "11kv"] },
  { label: 'New Moti bagh No.I', value: '11kvess-new-moti-bagh-no-i', route: '/crew-management', keywords: ["new", "moti", "bagh", "i", "11kvess", "substation", "11kv"] },
  { label: 'New Paid Ward (AIIMS)', value: '11kvess-new-paid-ward-aiims', route: '/crew-management', keywords: ["new", "paid", "ward", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'New Private Ward (AIIMS)', value: '11kvess-new-private-ward-aiims', route: '/crew-management', keywords: ["new", "private", "ward", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'Newzealand Embassy', value: '11kvess-newzealand-embassy', route: '/crew-management', keywords: ["newzealand", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Nigera Embassy', value: '11kvess-nigera-embassy', route: '/crew-management', keywords: ["nigera", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Nirman Bhawan', value: '11kvess-nirman-bhawan', route: '/crew-management', keywords: ["nirman", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Northen Railway', value: '11kvess-northen-railway', route: '/crew-management', keywords: ["northen", "railway", "11kvess", "substation", "11kv"] },
  { label: 'Norway Embassy', value: '11kvess-norway-embassy', route: '/crew-management', keywords: ["norway", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Oberai Hotel', value: '11kvess-oberai-hotel', route: '/crew-management', keywords: ["oberai", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'Orrisa Bhawan', value: '11kvess-orrisa-bhawan', route: '/crew-management', keywords: ["orrisa", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'PM Museum', value: '11kvess-pm-museum', route: '/crew-management', keywords: ["pm", "museum", "11kvess", "substation", "11kv"] },
  { label: 'P.C. Block (AIIMS)', value: '11kvess-p-c-block-aiims', route: '/crew-management', keywords: ["p", "c", "block", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'Palika Bhawan', value: '11kvess-palika-bhawan', route: '/crew-management', keywords: ["palika", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Pandara Park', value: '11kvess-pandara-park', route: '/crew-management', keywords: ["pandara", "park", "11kvess", "substation", "11kv"] },
  { label: 'Paryavaran Bhawan', value: '11kvess-paryavaran-bhawan', route: '/crew-management', keywords: ["paryavaran", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Phlastine Embassy', value: '11kvess-phlastine-embassy', route: '/crew-management', keywords: ["phlastine", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Pillanji Village (New)', value: '11kvess-pillanji-village-new', route: '/crew-management', keywords: ["pillanji", "village", "new", "11kvess", "substation", "11kv"] },
  { label: 'Pillanji Village(Old)', value: '11kvess-pillanji-village-old', route: '/crew-management', keywords: ["pillanji", "village", "old", "11kvess", "substation", "11kv"] },
  { label: 'Polish Embassy', value: '11kvess-polish-embassy', route: '/crew-management', keywords: ["polish", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Pravasi Bhartiya Kendra', value: '11kvess-pravasi-bhartiya-kendra', route: '/crew-management', keywords: ["pravasi", "bhartiya", "kendra", "11kvess", "substation", "11kv"] },
  { label: 'Qatar Embassy', value: '11kvess-qatar-embassy', route: '/crew-management', keywords: ["qatar", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'R.K. Puram No.1', value: '11kvess-r-k-puram-no-1', route: '/crew-management', keywords: ["r", "k", "puram", "1", "11kvess", "substation", "11kv"] },
  { label: 'R.K. puram No.2', value: '11kvess-r-k-puram-no-2', route: '/crew-management', keywords: ["r", "k", "puram", "2", "11kvess", "substation", "11kv"] },
  { label: 'R.P. center(AIIMS)', value: '11kvess-r-p-center-aiims', route: '/crew-management', keywords: ["r", "p", "center", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'Race Course(New)', value: '11kvess-race-course-new', route: '/crew-management', keywords: ["race", "course", "new", "11kvess", "substation", "11kv"] },
  { label: 'Race Course(Old)', value: '11kvess-race-course-old', route: '/crew-management', keywords: ["race", "course", "old", "11kvess", "substation", "11kv"] },
  { label: 'Railway Coloney-II', value: '11kvess-railway-coloney-ii', route: '/crew-management', keywords: ["railway", "coloney", "ii", "11kvess", "substation", "11kv"] },
  { label: 'Railway Computer Center', value: '11kvess-railway-computer-center', route: '/crew-management', keywords: ["railway", "computer", "center", "11kvess", "substation", "11kv"] },
  { label: 'Railway Officers Enclave Flats(Near Leela Hotel)', value: '11kvess-railway-officers-enclave-flats-near-leela-hotel', route: '/crew-management', keywords: ["railway", "officers", "enclave", "flats", "near", "leela", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'Railway Sec Board', value: '11kvess-railway-sec-board', route: '/crew-management', keywords: ["railway", "sec", "board", "11kvess", "substation", "11kv"] },
  { label: 'S.J. staff Qtr No.1', value: '11kvess-s-j-staff-qtr-no-1', route: '/crew-management', keywords: ["s", "j", "staff", "qtr", "1", "11kvess", "substation", "11kv"] },
  { label: 'S.J. Post office', value: '11kvess-s-j-post-office', route: '/crew-management', keywords: ["s", "j", "post", "office", "11kvess", "substation", "11kv"] },
  { label: 'S.J.H. Complex', value: '11kvess-s-j-h-complex', route: '/crew-management', keywords: ["s", "j", "h", "complex", "11kvess", "substation", "11kv"] },
  { label: 'Safdarjung Airport (New)', value: '11kvess-safdarjung-airport-new', route: '/crew-management', keywords: ["safdarjung", "airport", "new", "11kvess", "substation", "11kv"] },
  { label: 'Sanjay Camp 33/11 KV(Set No I)', value: '11kvess-sanjay-camp-33-11-kv-set-no-i', route: '/crew-management', keywords: ["sanjay", "camp", "33", "11", "set", "i", "11kvess", "substation", "11kv"] },
  { label: 'Sanskriti School', value: '11kvess-sanskriti-school', route: '/crew-management', keywords: ["sanskriti", "school", "11kvess", "substation", "11kv"] },
  { label: 'Satya Saadan', value: '11kvess-satya-saadan', route: '/crew-management', keywords: ["satya", "saadan", "11kvess", "substation", "11kv"] },
  { label: 'Saudi Arabia Embassy', value: '11kvess-saudi-arabia-embassy', route: '/crew-management', keywords: ["saudi", "arabia", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Shastri Niketan', value: '11kvess-shastri-niketan', route: '/crew-management', keywords: ["shastri", "niketan", "11kvess", "substation", "11kv"] },
  { label: 'Sikkim House', value: '11kvess-sikkim-house', route: '/crew-management', keywords: ["sikkim", "house", "11kvess", "substation", "11kv"] },
  { label: 'Social Infrastuctre Kidwai Nagar East', value: '11kvess-social-infrastuctre-kidwai-nagar-east', route: '/crew-management', keywords: ["social", "infrastuctre", "kidwai", "nagar", "east", "11kvess", "substation", "11kv"] },
  { label: 'South Avenue', value: '11kvess-south-avenue', route: '/crew-management', keywords: ["south", "avenue", "11kvess", "substation", "11kv"] },
  { label: 'South Block', value: '11kvess-south-block', route: '/crew-management', keywords: ["south", "block", "11kvess", "substation", "11kv"] },
  { label: 'Sport Injury Center', value: '11kvess-sport-injury-center', route: '/crew-management', keywords: ["sport", "injury", "center", "11kvess", "substation", "11kv"] },
  { label: 'State Guest House', value: '11kvess-state-guest-house', route: '/crew-management', keywords: ["state", "guest", "house", "11kvess", "substation", "11kv"] },
  { label: 'Tamil Nadu House Old', value: '11kvess-tamil-nadu-house-old', route: '/crew-management', keywords: ["tamil", "nadu", "house", "old", "11kvess", "substation", "11kv"] },
  { label: 'Tamil Nadu House', value: '11kvess-tamil-nadu-house', route: '/crew-management', keywords: ["tamil", "nadu", "house", "11kvess", "substation", "11kv"] },
  { label: 'Tanzania Embassy', value: '11kvess-tanzania-embassy', route: '/crew-management', keywords: ["tanzania", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Teaching Block (AIIMS)', value: '11kvess-teaching-block-aiims', route: '/crew-management', keywords: ["teaching", "block", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'ThaiLand Embassy', value: '11kvess-thailand-embassy', route: '/crew-management', keywords: ["thailand", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'TPT', value: '11kvess-tpt', route: '/crew-management', keywords: ["tpt", "11kvess", "substation", "11kv"] },
  { label: 'Transit hostel', value: '11kvess-transit-hostel', route: '/crew-management', keywords: ["transit", "hostel", "11kvess", "substation", "11kv"] },
  { label: 'Trauma Centre 33/11', value: '11kvess-trauma-centre-33-11', route: '/crew-management', keywords: ["trauma", "centre", "33", "11", "11kvess", "substation", "11kv"] },
  { label: 'Tripura House', value: '11kvess-tripura-house', route: '/crew-management', keywords: ["tripura", "house", "11kvess", "substation", "11kv"] },
  { label: 'Tughlak Lane', value: '11kvess-tughlak-lane', route: '/crew-management', keywords: ["tughlak", "lane", "11kvess", "substation", "11kv"] },
  { label: 'Tuglak Crescent', value: '11kvess-tuglak-crescent', route: '/crew-management', keywords: ["tuglak", "crescent", "11kvess", "substation", "11kv"] },
  { label: 'Turkey Embassey', value: '11kvess-turkey-embassey', route: '/crew-management', keywords: ["turkey", "embassey", "11kvess", "substation", "11kv"] },
  { label: 'U.K. High commission', value: '11kvess-u-k-high-commission', route: '/crew-management', keywords: ["u", "k", "high", "commission", "11kvess", "substation", "11kv"] },
  { label: 'U.P. Bhawan', value: '11kvess-u-p-bhawan', route: '/crew-management', keywords: ["u", "p", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'U.P. Sadan', value: '11kvess-u-p-sadan', route: '/crew-management', keywords: ["u", "p", "sadan", "11kvess", "substation", "11kv"] },
  { label: 'UAE Embassy', value: '11kvess-uae-embassy', route: '/crew-management', keywords: ["uae", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Uttrakhand Niwas', value: '11kvess-uttrakhand-niwas', route: '/crew-management', keywords: ["uttrakhand", "niwas", "11kvess", "substation", "11kv"] },
  { label: 'Uzbekistan Embassy', value: '11kvess-uzbekistan-embassy', route: '/crew-management', keywords: ["uzbekistan", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'Vanijay Bhawan', value: '11kvess-vanijay-bhawan', route: '/crew-management', keywords: ["vanijay", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Vayu Bhawan', value: '11kvess-vayu-bhawan', route: '/crew-management', keywords: ["vayu", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Veerawali Hospital', value: '11kvess-veerawali-hospital', route: '/crew-management', keywords: ["veerawali", "hospital", "11kvess", "substation", "11kv"] },
  { label: 'Vidyut Bhawan 11KV', value: '11kvess-vidyut-bhawan-11kv', route: '/crew-management', keywords: ["vidyut", "bhawan", "11kv", "11kvess", "substation"] },
  { label: 'Vishwa Yuvak Kendra', value: '11kvess-vishwa-yuvak-kendra', route: '/crew-management', keywords: ["vishwa", "yuvak", "kendra", "11kvess", "substation", "11kv"] },
  { label: 'Viyatnam', value: '11kvess-viyatnam', route: '/crew-management', keywords: ["viyatnam", "11kvess", "substation", "11kv"] },
  { label: 'Sports Injury Centre Safdarjung', value: '11kvess-sports-injury-centre-safdarjung', route: '/crew-management', keywords: ["sports", "injury", "centre", "safdarjung", "11kvess", "substation", "11kv"] },
  { label: 'PMS', value: '11kvess-pms', route: '/crew-management', keywords: ["pms", "11kvess", "substation", "11kv"] },
  { label: 'Northern railway, chankayapuri', value: '11kvess-northern-railway-chankayapuri', route: '/crew-management', keywords: ["northern", "railway", "chankayapuri", "11kvess", "substation", "11kv"] },
  { label: 'MP Bhawan Chankypuri', value: '11kvess-mp-bhawan-chankypuri', route: '/crew-management', keywords: ["mp", "bhawan", "chankypuri", "11kvess", "substation", "11kv"] },
  { label: '2A Mansingh road', value: '11kvess-2a-mansingh-road', route: '/crew-management', keywords: ["2a", "mansingh", "road", "11kvess", "substation", "11kv"] },
  { label: 'S block Delhi High Court', value: '11kvess-s-block-delhi-high-court', route: '/crew-management', keywords: ["s", "block", "delhi", "high", "court", "11kvess", "substation", "11kv"] },
  { label: 'Travencore house', value: '11kvess-travencore-house', route: '/crew-management', keywords: ["travencore", "house", "11kvess", "substation", "11kv"] },
  { label: 'Kaushal Bhawan', value: '11kvess-kaushal-bhawan', route: '/crew-management', keywords: ["kaushal", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'AIIMS Dental', value: '11kvess-aiims-dental', route: '/crew-management', keywords: ["aiims", "dental", "11kvess", "substation", "11kv"] },
  { label: 'W.T.I.', value: '11kvess-w-t-i', route: '/crew-management', keywords: ["w", "t", "i", "11kvess", "substation", "11kv"] },
  { label: 'Ward Block(AIIMS)', value: '11kvess-ward-block-aiims', route: '/crew-management', keywords: ["ward", "block", "aiims", "11kvess", "substation", "11kv"] },
  { label: 'World Bank', value: '11kvess-world-bank', route: '/crew-management', keywords: ["world", "bank", "11kvess", "substation", "11kv"] },
  { label: 'ESS No.6 (Copernicus Marg)', value: '11kvess-ess-no-6-copernicus-marg', route: '/crew-management', keywords: ["ess", "6", "copernicus", "marg", "11kvess", "substation", "11kv"] },
  { label: 'JEEVAN DEEP', value: '11kvess-jeevan-deep', route: '/crew-management', keywords: ["jeevan", "deep", "11kvess", "substation", "11kv"] },
  { label: 'LAWYER CHAMBER (New)', value: '11kvess-lawyer-chamber-new', route: '/crew-management', keywords: ["lawyer", "chamber", "new", "11kvess", "substation", "11kv"] },
  { label: 'MEGA CENTRE', value: '11kvess-mega-centre', route: '/crew-management', keywords: ["mega", "centre", "11kvess", "substation", "11kv"] },
  { label: 'NORTH AVENUE(OLD)', value: '11kvess-north-avenue-old', route: '/crew-management', keywords: ["north", "avenue", "old", "11kvess", "substation", "11kv"] },
  { label: 'R.P. LANE', value: '11kvess-r-p-lane', route: '/crew-management', keywords: ["r", "p", "lane", "11kvess", "substation", "11kv"] },
  { label: 'SHASTRI BHAWAN', value: '11kvess-shastri-bhawan', route: '/crew-management', keywords: ["shastri", "bhawan", "11kvess", "substation", "11kv"] },
  { label: '1 BHAGWAN DAS ROAD', value: '11kvess-1-bhagwan-das-road', route: '/crew-management', keywords: ["1", "bhagwan", "das", "road", "11kvess", "substation", "11kv"] },
  { label: '1 HAILEY ROAD', value: '11kvess-1-hailey-road', route: '/crew-management', keywords: ["1", "hailey", "road", "11kvess", "substation", "11kv"] },
  { label: '10 BHAGWAN DAS ROAD(White House)', value: '11kvess-10-bhagwan-das-road-white-house', route: '/crew-management', keywords: ["10", "bhagwan", "das", "road", "white", "house", "11kvess", "substation", "11kv"] },
  { label: '10 HAILEY ROAD (Dakshneswar)', value: '11kvess-10-hailey-road-dakshneswar', route: '/crew-management', keywords: ["10", "hailey", "road", "dakshneswar", "11kvess", "substation", "11kv"] },
  { label: '15 KG MARG MERCENTILE HOUSE', value: '11kvess-15-kg-marg-mercentile-house', route: '/crew-management', keywords: ["15", "kg", "marg", "mercentile", "house", "11kvess", "substation", "11kv"] },
  { label: '15-17 TOLSTOY MARG', value: '11kvess-15-17-tolstoy-marg', route: '/crew-management', keywords: ["15", "17", "tolstoy", "marg", "11kvess", "substation", "11kv"] },
  { label: '18 TILAK MARG', value: '11kvess-18-tilak-marg', route: '/crew-management', keywords: ["18", "tilak", "marg", "11kvess", "substation", "11kv"] },
  { label: '22 BARAKHAMBA ROAD', value: '11kvess-22-barakhamba-road', route: '/crew-management', keywords: ["22", "barakhamba", "road", "11kvess", "substation", "11kv"] },
  { label: '22 FEROZSHAH ROAD', value: '11kvess-22-ferozshah-road', route: '/crew-management', keywords: ["22", "ferozshah", "road", "11kvess", "substation", "11kv"] },
  { label: '22 TILAK MARG (College of Art)', value: '11kvess-22-tilak-marg-college-of-art', route: '/crew-management', keywords: ["22", "tilak", "marg", "college", "of", "art", "11kvess", "substation", "11kv"] },
  { label: '24 FEROZSHAH ROAD', value: '11kvess-24-ferozshah-road', route: '/crew-management', keywords: ["24", "ferozshah", "road", "11kvess", "substation", "11kv"] },
  { label: '2-4 RAFI MARG', value: '11kvess-2-4-rafi-marg', route: '/crew-management', keywords: ["2", "4", "rafi", "marg", "11kvess", "substation", "11kv"] },
  { label: '27 KG MARG', value: '11kvess-27-kg-marg', route: '/crew-management', keywords: ["27", "kg", "marg", "11kvess", "substation", "11kv"] },
  { label: '28 FEROZSHAH ROAD', value: '11kvess-28-ferozshah-road', route: '/crew-management', keywords: ["28", "ferozshah", "road", "11kvess", "substation", "11kv"] },
  { label: '3BD MARG', value: '11kvess-3bd-marg', route: '/crew-management', keywords: ["3bd", "marg", "11kvess", "substation", "11kv"] },
  { label: '30 FEROZSHAH ROAD', value: '11kvess-30-ferozshah-road', route: '/crew-management', keywords: ["30", "ferozshah", "road", "11kvess", "substation", "11kv"] },
  { label: '34 FIROZSHAHROAD', value: '11kvess-34-firozshahroad', route: '/crew-management', keywords: ["34", "firozshahroad", "11kvess", "substation", "11kv"] },
  { label: '35 FEROZSHAH ROAD', value: '11kvess-35-ferozshah-road', route: '/crew-management', keywords: ["35", "ferozshah", "road", "11kvess", "substation", "11kv"] },
  { label: '5 HAILEY ROAD', value: '11kvess-5-hailey-road', route: '/crew-management', keywords: ["5", "hailey", "road", "11kvess", "substation", "11kv"] },
  { label: '6 BHAGWAN DAS ROAD', value: '11kvess-6-bhagwan-das-road', route: '/crew-management', keywords: ["6", "bhagwan", "das", "road", "11kvess", "substation", "11kv"] },
  { label: '6 TILAK MARG(sagar Apartment)', value: '11kvess-6-tilak-marg-sagar-apartment', route: '/crew-management', keywords: ["6", "tilak", "marg", "sagar", "apartment", "11kvess", "substation", "11kv"] },
  { label: '66/11KV BD MARG', value: '11kvess-66-11kv-bd-marg', route: '/crew-management', keywords: ["66", "11kv", "bd", "marg", "11kvess", "substation"] },
  { label: '7 RAISINA ROAD (National Media Center)', value: '11kvess-7-raisina-road-national-media-center', route: '/crew-management', keywords: ["7", "raisina", "road", "national", "media", "center", "11kvess", "substation", "11kv"] },
  { label: '76 QUARTER B.D MARG', value: '11kvess-76-quarter-b-d-marg', route: '/crew-management', keywords: ["76", "quarter", "b", "d", "marg", "11kvess", "substation", "11kv"] },
  { label: '85 BLOCK (PUCHKUIYAN ROAD)', value: '11kvess-85-block-puchkuiyan-road', route: '/crew-management', keywords: ["85", "block", "puchkuiyan", "road", "11kvess", "substation", "11kv"] },
  { label: '9 BARAKHAMBA ROAD', value: '11kvess-9-barakhamba-road', route: '/crew-management', keywords: ["9", "barakhamba", "road", "11kvess", "substation", "11kv"] },
  { label: 'A-BLOCK', value: '11kvess-a-block', route: '/crew-management', keywords: ["a", "block", "11kvess", "substation", "11kv"] },
  { label: 'A.P. GUEST HOUSE', value: '11kvess-a-p-guest-house', route: '/crew-management', keywords: ["a", "p", "guest", "house", "11kvess", "substation", "11kv"] },
  { label: 'A.S.I. 24 TILAK MARG', value: '11kvess-a-s-i-24-tilak-marg', route: '/crew-management', keywords: ["a", "s", "i", "24", "tilak", "marg", "11kvess", "substation", "11kv"] },
  { label: 'AKANSHA', value: '11kvess-akansha', route: '/crew-management', keywords: ["akansha", "11kvess", "substation", "11kv"] },
  { label: 'AKASHDEEP BUILDING', value: '11kvess-akashdeep-building', route: '/crew-management', keywords: ["akashdeep", "building", "11kvess", "substation", "11kv"] },
  { label: 'Allahabad Bank', value: '11kvess-allahabad-bank', route: '/crew-management', keywords: ["allahabad", "bank", "11kvess", "substation", "11kv"] },
  { label: 'AMBADEEP BUILDING', value: '11kvess-ambadeep-building', route: '/crew-management', keywords: ["ambadeep", "building", "11kvess", "substation", "11kv"] },
  { label: 'AMBADKAR INTERNATIONAL CENTER', value: '11kvess-ambadkar-international-center', route: '/crew-management', keywords: ["ambadkar", "international", "center", "11kvess", "substation", "11kv"] },
  { label: 'ANSAL BHAWAN', value: '11kvess-ansal-bhawan', route: '/crew-management', keywords: ["ansal", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'ANTRIKSH BHAWAN', value: '11kvess-antriksh-bhawan', route: '/crew-management', keywords: ["antriksh", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'ARUNACHAL BUILDING', value: '11kvess-arunachal-building', route: '/crew-management', keywords: ["arunachal", "building", "11kvess", "substation", "11kv"] },
  { label: 'Ashadeep', value: '11kvess-ashadeep', route: '/crew-management', keywords: ["ashadeep", "11kvess", "substation", "11kv"] },
  { label: 'ASHOKA ESTATE', value: '11kvess-ashoka-estate', route: '/crew-management', keywords: ["ashoka", "estate", "11kvess", "substation", "11kv"] },
  { label: 'ATMARAM HOUSE', value: '11kvess-atmaram-house', route: '/crew-management', keywords: ["atmaram", "house", "11kvess", "substation", "11kv"] },
  { label: 'B.S.N.L.', value: '11kvess-b-s-n-l', route: '/crew-management', keywords: ["b", "s", "n", "l", "11kvess", "substation", "11kv"] },
  { label: 'BAIRD LANE', value: '11kvess-baird-lane', route: '/crew-management', keywords: ["baird", "lane", "11kvess", "substation", "11kv"] },
  { label: 'BANG BHAWAN(3 Hailey Road)', value: '11kvess-bang-bhawan-3-hailey-road', route: '/crew-management', keywords: ["bang", "bhawan", "3", "hailey", "road", "11kvess", "substation", "11kv"] },
  { label: 'BB TANK', value: '11kvess-bb-tank', route: '/crew-management', keywords: ["bb", "tank", "11kvess", "substation", "11kv"] },
  { label: 'Bhai Veer Singh Marg', value: '11kvess-bhai-veer-singh-marg', route: '/crew-management', keywords: ["bhai", "veer", "singh", "marg", "11kvess", "substation", "11kv"] },
  { label: 'BHARAT HOTEL', value: '11kvess-bharat-hotel', route: '/crew-management', keywords: ["bharat", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'BHARTIYA VIDHYA BHAWAN', value: '11kvess-bhartiya-vidhya-bhawan', route: '/crew-management', keywords: ["bhartiya", "vidhya", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'BHAWALPUR HOUSE (NSD)', value: '11kvess-bhawalpur-house-nsd', route: '/crew-management', keywords: ["bhawalpur", "house", "nsd", "11kvess", "substation", "11kv"] },
  { label: 'BIRLA TOWER', value: '11kvess-birla-tower', route: '/crew-management', keywords: ["birla", "tower", "11kvess", "substation", "11kv"] },
  { label: 'BKS-I', value: '11kvess-bks-i', route: '/crew-management', keywords: ["bks", "i", "11kvess", "substation", "11kv"] },
  { label: 'BKS-II (A & B Board)', value: '11kvess-bks-ii-a-b-board', route: '/crew-management', keywords: ["bks", "ii", "a", "b", "board", "11kvess", "substation", "11kv"] },
  { label: 'BOMBAY LIFE BUILDING', value: '11kvess-bombay-life-building', route: '/crew-management', keywords: ["bombay", "life", "building", "11kvess", "substation", "11kv"] },
  { label: 'BRITISH COUNCIL', value: '11kvess-british-council', route: '/crew-management', keywords: ["british", "council", "11kvess", "substation", "11kv"] },
  { label: 'BSNL', value: '11kvess-bsnl', route: '/crew-management', keywords: ["bsnl", "11kvess", "substation", "11kv"] },
  { label: 'C.S.I.R', value: '11kvess-c-s-i-r', route: '/crew-management', keywords: ["c", "s", "i", "r", "11kvess", "substation", "11kv"] },
  { label: 'C.S.O.I', value: '11kvess-c-s-o-i', route: '/crew-management', keywords: ["c", "s", "o", "i", "11kvess", "substation", "11kv"] },
  { label: 'CANNING LANE', value: '11kvess-canning-lane', route: '/crew-management', keywords: ["canning", "lane", "11kvess", "substation", "11kv"] },
  { label: 'CEMENT GODWAN', value: '11kvess-cement-godwan', route: '/crew-management', keywords: ["cement", "godwan", "11kvess", "substation", "11kv"] },
  { label: 'Chandralok Building', value: '11kvess-chandralok-building', route: '/crew-management', keywords: ["chandralok", "building", "11kvess", "substation", "11kv"] },
  { label: 'CHELMSFORD CLUB', value: '11kvess-chelmsford-club', route: '/crew-management', keywords: ["chelmsford", "club", "11kvess", "substation", "11kv"] },
  { label: 'Clivesquare', value: '11kvess-clivesquare', route: '/crew-management', keywords: ["clivesquare", "11kvess", "substation", "11kv"] },
  { label: 'CNI', value: '11kvess-cni', route: '/crew-management', keywords: ["cni", "11kvess", "substation", "11kv"] },
  { label: 'CONNAUGHT CIRCUS', value: '11kvess-connaught-circus', route: '/crew-management', keywords: ["connaught", "circus", "11kvess", "substation", "11kv"] },
  { label: 'Connaught Hotel', value: '11kvess-connaught-hotel', route: '/crew-management', keywords: ["connaught", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'CONNAUGHT PLACE NEW BUILDING', value: '11kvess-connaught-place-new-building', route: '/crew-management', keywords: ["connaught", "place", "new", "building", "11kvess", "substation", "11kv"] },
  { label: 'CONNAUGHT PLACE OLD BUILDING', value: '11kvess-connaught-place-old-building', route: '/crew-management', keywords: ["connaught", "place", "old", "building", "11kvess", "substation", "11kv"] },
  { label: 'CPRTI', value: '11kvess-cprti', route: '/crew-management', keywords: ["cprti", "11kvess", "substation", "11kv"] },
  { label: 'DCM BUILDING', value: '11kvess-dcm-building', route: '/crew-management', keywords: ["dcm", "building", "11kvess", "substation", "11kv"] },
  { label: 'District Centre', value: '11kvess-district-centre', route: '/crew-management', keywords: ["district", "centre", "11kvess", "substation", "11kv"] },
  { label: 'DLF BUILDING', value: '11kvess-dlf-building', route: '/crew-management', keywords: ["dlf", "building", "11kvess", "substation", "11kv"] },
  { label: 'DLF Car Parking', value: '11kvess-dlf-car-parking', route: '/crew-management', keywords: ["dlf", "car", "parking", "11kvess", "substation", "11kv"] },
  { label: 'DMRC', value: '11kvess-dmrc', route: '/crew-management', keywords: ["dmrc", "11kvess", "substation", "11kv"] },
  { label: 'DTL 220 PARK STREET', value: '11kvess-dtl-220-park-street', route: '/crew-management', keywords: ["dtl", "220", "park", "street", "11kvess", "substation", "11kv"] },
  { label: 'ELECTION COMMISSION', value: '11kvess-election-commission', route: '/crew-management', keywords: ["election", "commission", "11kvess", "substation", "11kv"] },
  { label: 'ESS 33/11KV RAJA BAZAR', value: '11kvess-ess-33-11kv-raja-bazar', route: '/crew-management', keywords: ["ess", "33", "11kv", "raja", "bazar", "11kvess", "substation"] },
  { label: 'ESS NDCC PHASE-II', value: '11kvess-ess-ndcc-phase-ii', route: '/crew-management', keywords: ["ess", "ndcc", "phase", "ii", "11kvess", "substation", "11kv"] },
  { label: 'ESS No.3(New) with CR panels', value: '11kvess-ess-no-3-new-with-cr-panels', route: '/crew-management', keywords: ["ess", "3", "new", "with", "cr", "panels", "11kvess", "substation", "11kv"] },
  { label: 'ESS No.3(old)', value: '11kvess-ess-no-3-old', route: '/crew-management', keywords: ["ess", "3", "old", "11kvess", "substation", "11kv"] },
  { label: 'FARIDKOT HOUSE', value: '11kvess-faridkot-house', route: '/crew-management', keywords: ["faridkot", "house", "11kvess", "substation", "11kv"] },
  { label: 'FCI BUILDING', value: '11kvess-fci-building', route: '/crew-management', keywords: ["fci", "building", "11kvess", "substation", "11kv"] },
  { label: 'FICCI', value: '11kvess-ficci', route: '/crew-management', keywords: ["ficci", "11kvess", "substation", "11kv"] },
  { label: 'GOLEMARKET', value: '11kvess-golemarket', route: '/crew-management', keywords: ["golemarket", "11kvess", "substation", "11kv"] },
  { label: 'GOPALDASS BUILDING', value: '11kvess-gopaldass-building', route: '/crew-management', keywords: ["gopaldass", "building", "11kvess", "substation", "11kv"] },
  { label: 'G-Point', value: '11kvess-g-point', route: '/crew-management', keywords: ["g", "point", "11kvess", "substation", "11kv"] },
  { label: 'Gurudwara Bangla sahib', value: '11kvess-gurudwara-bangla-sahib', route: '/crew-management', keywords: ["gurudwara", "bangla", "sahib", "11kvess", "substation", "11kv"] },
  { label: 'HANDLOOM HOUSE JANPATH LANE', value: '11kvess-handloom-house-janpath-lane', route: '/crew-management', keywords: ["handloom", "house", "janpath", "lane", "11kvess", "substation", "11kv"] },
  { label: 'Hansalay', value: '11kvess-hansalay', route: '/crew-management', keywords: ["hansalay", "11kvess", "substation", "11kv"] },
  { label: 'HANUMAN ROAD (OLD)', value: '11kvess-hanuman-road-old', route: '/crew-management', keywords: ["hanuman", "road", "old", "11kvess", "substation", "11kv"] },
  { label: 'HANUMAN ROAD NEW \'A\' BOARD', value: '11kvess-hanuman-road-new-a-board', route: '/crew-management', keywords: ["hanuman", "road", "new", "a", "board", "11kvess", "substation", "11kv"] },
  { label: 'HARYANA BHAWAN', value: '11kvess-haryana-bhawan', route: '/crew-management', keywords: ["haryana", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'HAVLAQ SQUARE', value: '11kvess-havlaq-square', route: '/crew-management', keywords: ["havlaq", "square", "11kvess", "substation", "11kv"] },
  { label: 'HCM LANE DTL 220 KVA', value: '11kvess-hcm-lane-dtl-220-kva', route: '/crew-management', keywords: ["hcm", "lane", "dtl", "220", "kva", "11kvess", "substation", "11kv"] },
  { label: 'HIGH COURT CAR PARKING', value: '11kvess-high-court-car-parking', route: '/crew-management', keywords: ["high", "court", "car", "parking", "11kvess", "substation", "11kv"] },
  { label: 'Park street ESS', value: '11kvess-park-street-ess', route: '/crew-management', keywords: ["park", "street", "ess", "11kvess", "substation", "11kv"] },
  { label: 'HIMALAYA HOUSE', value: '11kvess-himalaya-house', route: '/crew-management', keywords: ["himalaya", "house", "11kvess", "substation", "11kv"] },
  { label: 'HOTEL SANGRILA', value: '11kvess-hotel-sangrila', route: '/crew-management', keywords: ["hotel", "sangrila", "11kvess", "substation", "11kv"] },
  { label: 'I.A.C.', value: '11kvess-i-a-c', route: '/crew-management', keywords: ["i", "a", "c", "11kvess", "substation", "11kv"] },
  { label: 'I.E.N.S.', value: '11kvess-i-e-n-s', route: '/crew-management', keywords: ["i", "e", "n", "s", "11kvess", "substation", "11kv"] },
  { label: 'I.G.N.C.A. (Janpath Hotel)', value: '11kvess-i-g-n-c-a-janpath-hotel', route: '/crew-management', keywords: ["i", "g", "n", "c", "a", "janpath", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'I.N.T.', value: '11kvess-i-n-t', route: '/crew-management', keywords: ["i", "n", "t", "11kvess", "substation", "11kv"] },
  { label: 'ICE FACTORY', value: '11kvess-ice-factory', route: '/crew-management', keywords: ["ice", "factory", "11kvess", "substation", "11kv"] },
  { label: 'INDERPRAKASH BUILDING', value: '11kvess-inderprakash-building', route: '/crew-management', keywords: ["inderprakash", "building", "11kvess", "substation", "11kv"] },
  { label: 'INDIAN COAST GUARD', value: '11kvess-indian-coast-guard', route: '/crew-management', keywords: ["indian", "coast", "guard", "11kvess", "substation", "11kv"] },
  { label: 'INDIAN OIL BHAWAN', value: '11kvess-indian-oil-bhawan', route: '/crew-management', keywords: ["indian", "oil", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'IPPO Speed Post', value: '11kvess-ippo-speed-post', route: '/crew-management', keywords: ["ippo", "speed", "post", "11kvess", "substation", "11kv"] },
  { label: 'J. POINT', value: '11kvess-j-point', route: '/crew-management', keywords: ["j", "point", "11kvess", "substation", "11kv"] },
  { label: 'JAISINGH ROAD', value: '11kvess-jaisingh-road', route: '/crew-management', keywords: ["jaisingh", "road", "11kvess", "substation", "11kv"] },
  { label: 'JAWAHAR BHAWAN', value: '11kvess-jawahar-bhawan', route: '/crew-management', keywords: ["jawahar", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'JEEVAN BHARTI', value: '11kvess-jeevan-bharti', route: '/crew-management', keywords: ["jeevan", "bharti", "11kvess", "substation", "11kv"] },
  { label: 'JEEVAN VIHAR', value: '11kvess-jeevan-vihar', route: '/crew-management', keywords: ["jeevan", "vihar", "11kvess", "substation", "11kv"] },
  { label: 'KAILASH BUILDING', value: '11kvess-kailash-building', route: '/crew-management', keywords: ["kailash", "building", "11kvess", "substation", "11kv"] },
  { label: 'KALAWATI SARAN', value: '11kvess-kalawati-saran', route: '/crew-management', keywords: ["kalawati", "saran", "11kvess", "substation", "11kv"] },
  { label: 'KALIBARI MARG', value: '11kvess-kalibari-marg', route: '/crew-management', keywords: ["kalibari", "marg", "11kvess", "substation", "11kv"] },
  { label: 'KANCHANJUNGA BUILDING', value: '11kvess-kanchanjunga-building', route: '/crew-management', keywords: ["kanchanjunga", "building", "11kvess", "substation", "11kv"] },
  { label: 'KERALA HOUSE', value: '11kvess-kerala-house', route: '/crew-management', keywords: ["kerala", "house", "11kvess", "substation", "11kv"] },
  { label: 'KRISHI BHAWAN With CR panels', value: '11kvess-krishi-bhawan-with-cr-panels', route: '/crew-management', keywords: ["krishi", "bhawan", "with", "cr", "panels", "11kvess", "substation", "11kv"] },
  { label: 'LADY HARDING HOSPITAL', value: '11kvess-lady-harding-hospital', route: '/crew-management', keywords: ["lady", "harding", "hospital", "11kvess", "substation", "11kv"] },
  { label: 'Lady Harding Hospital Staff Quarter', value: '11kvess-lady-harding-hospital-staff-quarter', route: '/crew-management', keywords: ["lady", "harding", "hospital", "staff", "quarter", "11kvess", "substation", "11kv"] },
  { label: 'LAWYER CHAMBER SUPREME COURT', value: '11kvess-lawyer-chamber-supreme-court', route: '/crew-management', keywords: ["lawyer", "chamber", "supreme", "court", "11kvess", "substation", "11kv"] },
  { label: 'LIC BUILDING', value: '11kvess-lic-building', route: '/crew-management', keywords: ["lic", "building", "11kvess", "substation", "11kv"] },
  { label: 'MANDI HOUSE', value: '11kvess-mandi-house', route: '/crew-management', keywords: ["mandi", "house", "11kvess", "substation", "11kv"] },
  { label: 'MARINA HOTEL', value: '11kvess-marina-hotel', route: '/crew-management', keywords: ["marina", "hotel", "11kvess", "substation", "11kv"] },
  { label: 'MAYUR BHAWAN', value: '11kvess-mayur-bhawan', route: '/crew-management', keywords: ["mayur", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'MEGHDOOT BHAWAN', value: '11kvess-meghdoot-bhawan', route: '/crew-management', keywords: ["meghdoot", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'MINTO ROAD', value: '11kvess-minto-road', route: '/crew-management', keywords: ["minto", "road", "11kvess", "substation", "11kv"] },
  { label: 'MODERN SCHOOL', value: '11kvess-modern-school', route: '/crew-management', keywords: ["modern", "school", "11kvess", "substation", "11kv"] },
  { label: 'Mohan dev', value: '11kvess-mohan-dev', route: '/crew-management', keywords: ["mohan", "dev", "11kvess", "substation", "11kv"] },
  { label: 'MOHAN SIGH PLACE', value: '11kvess-mohan-sigh-place', route: '/crew-management', keywords: ["mohan", "sigh", "place", "11kvess", "substation", "11kv"] },
  { label: 'N.S.C.I.', value: '11kvess-n-s-c-i', route: '/crew-management', keywords: ["n", "s", "c", "i", "11kvess", "substation", "11kv"] },
  { label: 'NAI(New) RECORD OFFICE', value: '11kvess-nai-new-record-office', route: '/crew-management', keywords: ["nai", "new", "record", "office", "11kvess", "substation", "11kv"] },
  { label: 'NAI(Old) with CR Panel', value: '11kvess-nai-old-with-cr-panel', route: '/crew-management', keywords: ["nai", "old", "with", "cr", "panel", "11kvess", "substation", "11kv"] },
  { label: 'NATIONAL STADIUM', value: '11kvess-national-stadium', route: '/crew-management', keywords: ["national", "stadium", "11kvess", "substation", "11kv"] },
  { label: 'NATIONAL WAR MEMORIAL', value: '11kvess-national-war-memorial', route: '/crew-management', keywords: ["national", "war", "memorial", "11kvess", "substation", "11kv"] },
  { label: 'NAVRANG HOUSE', value: '11kvess-navrang-house', route: '/crew-management', keywords: ["navrang", "house", "11kvess", "substation", "11kv"] },
  { label: 'NDCR', value: '11kvess-ndcr', route: '/crew-management', keywords: ["ndcr", "11kvess", "substation", "11kv"] },
  { label: 'NEPAL EMBASSY', value: '11kvess-nepal-embassy', route: '/crew-management', keywords: ["nepal", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'NEW DEFENCE OFFICE K.G. MARG', value: '11kvess-new-defence-office-k-g-marg', route: '/crew-management', keywords: ["new", "defence", "office", "k", "g", "marg", "11kvess", "substation", "11kv"] },
  { label: 'NEWDELHI HOUSE', value: '11kvess-newdelhi-house', route: '/crew-management', keywords: ["newdelhi", "house", "11kvess", "substation", "11kv"] },
  { label: 'NEW PLAZA', value: '11kvess-new-plaza', route: '/crew-management', keywords: ["new", "plaza", "11kvess", "substation", "11kv"] },
  { label: 'NIRMAL TOWER', value: '11kvess-nirmal-tower', route: '/crew-management', keywords: ["nirmal", "tower", "11kvess", "substation", "11kv"] },
  { label: 'NITI AYOG(Yojna Bhawan)', value: '11kvess-niti-ayog-yojna-bhawan', route: '/crew-management', keywords: ["niti", "ayog", "yojna", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'NORTH AVENU(NEW)', value: '11kvess-north-avenu-new', route: '/crew-management', keywords: ["north", "avenu", "new", "11kvess", "substation", "11kv"] },
  { label: 'OFFICE BLOCK', value: '11kvess-office-block', route: '/crew-management', keywords: ["office", "block", "11kvess", "substation", "11kv"] },
  { label: 'P.T.I.', value: '11kvess-p-t-i', route: '/crew-management', keywords: ["p", "t", "i", "11kvess", "substation", "11kv"] },
  { label: 'PALIKA BAZAR', value: '11kvess-palika-bazar', route: '/crew-management', keywords: ["palika", "bazar", "11kvess", "substation", "11kv"] },
  { label: 'PALIKA KENDRA', value: '11kvess-palika-kendra', route: '/crew-management', keywords: ["palika", "kendra", "11kvess", "substation", "11kv"] },
  { label: 'PALIKA PLACE', value: '11kvess-palika-place', route: '/crew-management', keywords: ["palika", "place", "11kvess", "substation", "11kv"] },
  { label: 'Parliament Library', value: '11kvess-parliament-library', route: '/crew-management', keywords: ["parliament", "library", "11kvess", "substation", "11kv"] },
  { label: 'PATIALA HOUSE', value: '11kvess-patiala-house', route: '/crew-management', keywords: ["patiala", "house", "11kvess", "substation", "11kv"] },
  { label: 'Peshwa Road', value: '11kvess-peshwa-road', route: '/crew-management', keywords: ["peshwa", "road", "11kvess", "substation", "11kv"] },
  { label: 'Police Head Quarter', value: '11kvess-police-head-quarter', route: '/crew-management', keywords: ["police", "head", "quarter", "11kvess", "substation", "11kv"] },
  { label: 'POLICE STATION MANDIR MARG', value: '11kvess-police-station-mandir-marg', route: '/crew-management', keywords: ["police", "station", "mandir", "marg", "11kvess", "substation", "11kv"] },
  { label: 'PRAKASHDEEP BUILDING', value: '11kvess-prakashdeep-building', route: '/crew-management', keywords: ["prakashdeep", "building", "11kvess", "substation", "11kv"] },
  { label: 'Pump House', value: '11kvess-pump-house', route: '/crew-management', keywords: ["pump", "house", "11kvess", "substation", "11kv"] },
  { label: 'PUNJAB BHAWAN', value: '11kvess-punjab-bhawan', route: '/crew-management', keywords: ["punjab", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'RAIL BHAWAN', value: '11kvess-rail-bhawan', route: '/crew-management', keywords: ["rail", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'RAISINA ROAD with CR Panel', value: '11kvess-raisina-road-with-cr-panel', route: '/crew-management', keywords: ["raisina", "road", "with", "cr", "panel", "11kvess", "substation", "11kv"] },
  { label: 'RAKSHA BHAWAN', value: '11kvess-raksha-bhawan', route: '/crew-management', keywords: ["raksha", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Ravinder Rang Sala', value: '11kvess-ravinder-rang-sala', route: '/crew-management', keywords: ["ravinder", "rang", "sala", "11kvess", "substation", "11kv"] },
  { label: 'RAVINDRA BHAWAN', value: '11kvess-ravindra-bhawan', route: '/crew-management', keywords: ["ravindra", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'Raza Bazar No.6', value: '11kvess-raza-bazar-no-6', route: '/crew-management', keywords: ["raza", "bazar", "6", "11kvess", "substation", "11kv"] },
  { label: 'RAZA BAZAR NO.8', value: '11kvess-raza-bazar-no-8', route: '/crew-management', keywords: ["raza", "bazar", "8", "11kvess", "substation", "11kv"] },
  { label: 'RED CROSS', value: '11kvess-red-cross', route: '/crew-management', keywords: ["red", "cross", "11kvess", "substation", "11kv"] },
  { label: 'RESERVE BANK', value: '11kvess-reserve-bank', route: '/crew-management', keywords: ["reserve", "bank", "11kvess", "substation", "11kv"] },
  { label: 'RML New Emergency', value: '11kvess-rml-new-emergency', route: '/crew-management', keywords: ["rml", "new", "emergency", "11kvess", "substation", "11kv"] },
  { label: 'ROHIT HOUSE', value: '11kvess-rohit-house', route: '/crew-management', keywords: ["rohit", "house", "11kvess", "substation", "11kv"] },
  { label: 'ROYAL PLAZA(Ashok Yatri Niwas)', value: '11kvess-royal-plaza-ashok-yatri-niwas', route: '/crew-management', keywords: ["royal", "plaza", "ashok", "yatri", "niwas", "11kvess", "substation", "11kv"] },
  { label: 'S.T.C (with CR Panels)', value: '11kvess-s-t-c-with-cr-panels', route: '/crew-management', keywords: ["s", "t", "c", "with", "cr", "panels", "11kvess", "substation", "11kv"] },
  { label: 'SANGLI MESS', value: '11kvess-sangli-mess', route: '/crew-management', keywords: ["sangli", "mess", "11kvess", "substation", "11kv"] },
  { label: 'SANITORY STORE', value: '11kvess-sanitory-store', route: '/crew-management', keywords: ["sanitory", "store", "11kvess", "substation", "11kv"] },
  { label: 'SAPRU HOUSE', value: '11kvess-sapru-house', route: '/crew-management', keywords: ["sapru", "house", "11kvess", "substation", "11kv"] },
  { label: 'SBI', value: '11kvess-sbi', route: '/crew-management', keywords: ["sbi", "11kvess", "substation", "11kv"] },
  { label: 'SCHOOL LANE', value: '11kvess-school-lane', route: '/crew-management', keywords: ["school", "lane", "11kvess", "substation", "11kv"] },
  { label: 'SCINDIA HOUSE', value: '11kvess-scindia-house', route: '/crew-management', keywords: ["scindia", "house", "11kvess", "substation", "11kv"] },
  { label: 'SCINDIA ROAD', value: '11kvess-scindia-road', route: '/crew-management', keywords: ["scindia", "road", "11kvess", "substation", "11kv"] },
  { label: 'SHIVAJI STADIUM (NEW)', value: '11kvess-shivaji-stadium-new', route: '/crew-management', keywords: ["shivaji", "stadium", "new", "11kvess", "substation", "11kv"] },
  { label: 'SHIVAJI STADIUM (OLD)', value: '11kvess-shivaji-stadium-old', route: '/crew-management', keywords: ["shivaji", "stadium", "old", "11kvess", "substation", "11kv"] },
  { label: 'Smog Tower', value: '11kvess-smog-tower', route: '/crew-management', keywords: ["smog", "tower", "11kvess", "substation", "11kv"] },
  { label: 'STATE EMPORIUM', value: '11kvess-state-emporium', route: '/crew-management', keywords: ["state", "emporium", "11kvess", "substation", "11kv"] },
  { label: 'SUNAIR HOTAL', value: '11kvess-sunair-hotal', route: '/crew-management', keywords: ["sunair", "hotal", "11kvess", "substation", "11kv"] },
  { label: 'SUPER BAZAR', value: '11kvess-super-bazar', route: '/crew-management', keywords: ["super", "bazar", "11kvess", "substation", "11kv"] },
  { label: 'SUPREME COURT', value: '11kvess-supreme-court', route: '/crew-management', keywords: ["supreme", "court", "11kvess", "substation", "11kv"] },
  { label: 'SURYA KIRAN BUILDING', value: '11kvess-surya-kiran-building', route: '/crew-management', keywords: ["surya", "kiran", "building", "11kvess", "substation", "11kv"] },
  { label: 'SWATI HOSTAL', value: '11kvess-swati-hostal', route: '/crew-management', keywords: ["swati", "hostal", "11kvess", "substation", "11kv"] },
  { label: 'Swimming Pool', value: '11kvess-swimming-pool', route: '/crew-management', keywords: ["swimming", "pool", "11kvess", "substation", "11kv"] },
  { label: 'T.R.C', value: '11kvess-t-r-c', route: '/crew-management', keywords: ["t", "r", "c", "11kvess", "substation", "11kv"] },
  { label: 'TALKATORA INDOOR STADIUM', value: '11kvess-talkatora-indoor-stadium', route: '/crew-management', keywords: ["talkatora", "indoor", "stadium", "11kvess", "substation", "11kv"] },
  { label: 'THAPAR HOUSE', value: '11kvess-thapar-house', route: '/crew-management', keywords: ["thapar", "house", "11kvess", "substation", "11kv"] },
  { label: 'TILAK MARG', value: '11kvess-tilak-marg', route: '/crew-management', keywords: ["tilak", "marg", "11kvess", "substation", "11kv"] },
  { label: 'TODER MAL LANE', value: '11kvess-toder-mal-lane', route: '/crew-management', keywords: ["toder", "mal", "lane", "11kvess", "substation", "11kv"] },
  { label: 'UDYAN MARG', value: '11kvess-udyan-marg', route: '/crew-management', keywords: ["udyan", "marg", "11kvess", "substation", "11kv"] },
  { label: 'UIDAI, AADHAR BUILDING', value: '11kvess-uidai-aadhar-building', route: '/crew-management', keywords: ["uidai", "aadhar", "building", "11kvess", "substation", "11kv"] },
  { label: 'VANDANA BUILDING', value: '11kvess-vandana-building', route: '/crew-management', keywords: ["vandana", "building", "11kvess", "substation", "11kv"] },
  { label: 'VANKATESHESWARA SWAMY TEMPLE', value: '11kvess-vankatesheswara-swamy-temple', route: '/crew-management', keywords: ["vankatesheswara", "swamy", "temple", "11kvess", "substation", "11kv"] },
  { label: 'VIJAY BUILDING', value: '11kvess-vijay-building', route: '/crew-management', keywords: ["vijay", "building", "11kvess", "substation", "11kv"] },
  { label: 'WESTERN COURT', value: '11kvess-western-court', route: '/crew-management', keywords: ["western", "court", "11kvess", "substation", "11kv"] },
  { label: 'South India Club Mandir Marg', value: '11kvess-south-india-club-mandir-marg', route: '/crew-management', keywords: ["south", "india", "club", "mandir", "marg", "11kvess", "substation", "11kv"] },
  { label: 'VP House', value: '11kvess-vp-house', route: '/crew-management', keywords: ["vp", "house", "11kvess", "substation", "11kv"] },
  { label: 'Vidut bhawan shankar market', value: '11kvess-vidut-bhawan-shankar-market', route: '/crew-management', keywords: ["vidut", "bhawan", "shankar", "market", "11kvess", "substation", "11kv"] },
  { label: 'Y.M.C.A.', value: '11kvess-y-m-c-a', route: '/crew-management', keywords: ["y", "m", "c", "a", "11kvess", "substation", "11kv"] },
  { label: 'Y.W.C.A.', value: '11kvess-y-w-c-a', route: '/crew-management', keywords: ["y", "w", "c", "a", "11kvess", "substation", "11kv"] },
  { label: 'Palika car parking', value: '11kvess-palika-car-parking', route: '/crew-management', keywords: ["palika", "car", "parking", "11kvess", "substation", "11kv"] },
  { label: 'CSS-6', value: '11kvess-css-6', route: '/crew-management', keywords: ["css", "6", "11kvess", "substation", "11kv"] },
  { label: 'M BLOCK', value: '11kvess-m-block', route: '/crew-management', keywords: ["m", "block", "11kvess", "substation", "11kv"] },
  { label: 'N BLOCK', value: '11kvess-n-block', route: '/crew-management', keywords: ["n", "block", "11kvess", "substation", "11kv"] },
  { label: 'RR1', value: '11kvess-rr1', route: '/crew-management', keywords: ["rr1", "11kvess", "substation", "11kv"] },
  { label: 'RR2', value: '11kvess-rr2', route: '/crew-management', keywords: ["rr2", "11kvess", "substation", "11kv"] },
  { label: 'RR3', value: '11kvess-rr3', route: '/crew-management', keywords: ["rr3", "11kvess", "substation", "11kv"] },
  { label: 'RR4', value: '11kvess-rr4', route: '/crew-management', keywords: ["rr4", "11kvess", "substation", "11kv"] },
  { label: 'RR5', value: '11kvess-rr5', route: '/crew-management', keywords: ["rr5", "11kvess", "substation", "11kv"] },
  { label: 'RR6', value: '11kvess-rr6', route: '/crew-management', keywords: ["rr6", "11kvess", "substation", "11kv"] },
  { label: 'USS at 26 Akbar Road', value: '11kvess-uss-at-26-akbar-road', route: '/crew-management', keywords: ["uss", "at", "26", "akbar", "road", "11kvess", "substation", "11kv"] },
  { label: 'USS at Charak Palika Hospital No.1 Moti Bagh(W)', value: '11kvess-uss-at-charak-palika-hospital-no-1-moti-bagh-w', route: '/crew-management', keywords: ["uss", "at", "charak", "palika", "hospital", "1", "moti", "bagh", "w", "11kvess", "substation", "11kv"] },
  { label: 'USS at Hanger No.IV S.J. AirPart', value: '11kvess-uss-at-hanger-no-iv-s-j-airpart', route: '/crew-management', keywords: ["uss", "at", "hanger", "iv", "s", "j", "airpart", "11kvess", "substation", "11kv"] },
  { label: 'USS at Palika Niwas', value: '11kvess-uss-at-palika-niwas', route: '/crew-management', keywords: ["uss", "at", "palika", "niwas", "11kvess", "substation", "11kv"] },
  { label: 'USS at Pillanji Village', value: '11kvess-uss-at-pillanji-village', route: '/crew-management', keywords: ["uss", "at", "pillanji", "village", "11kvess", "substation", "11kv"] },
  { label: 'USS at Prithive Raj Market', value: '11kvess-uss-at-prithive-raj-market', route: '/crew-management', keywords: ["uss", "at", "prithive", "raj", "market", "11kvess", "substation", "11kv"] },
  { label: 'USS at Barat Ghar Khan Market', value: '11kvess-uss-at-barat-ghar-khan-market', route: '/crew-management', keywords: ["uss", "at", "barat", "ghar", "khan", "market", "11kvess", "substation", "11kv"] },
  { label: 'USS at Charak Palika Hospital No.1 Moti Bagh(W)', value: '11kvess-uss-at-charak-palika-hospital-no-1-moti-bagh-w', route: '/crew-management', keywords: ["uss", "at", "charak", "palika", "hospital", "1", "moti", "bagh", "w", "11kvess", "substation", "11kv"] },
  { label: 'USS at Charak Palika Hospital No.2 Moti Bagh(W)', value: '11kvess-uss-at-charak-palika-hospital-no-2-moti-bagh-w', route: '/crew-management', keywords: ["uss", "at", "charak", "palika", "hospital", "2", "moti", "bagh", "w", "11kvess", "substation", "11kv"] },
  { label: 'USS at Children Park', value: '11kvess-uss-at-children-park', route: '/crew-management', keywords: ["uss", "at", "children", "park", "11kvess", "substation", "11kv"] },
  { label: 'USS at CNG Station Shanti Path', value: '11kvess-uss-at-cng-station-shanti-path', route: '/crew-management', keywords: ["uss", "at", "cng", "station", "shanti", "path", "11kvess", "substation", "11kv"] },
  { label: 'USS at DelhiPublic Library', value: '11kvess-uss-at-delhipublic-library', route: '/crew-management', keywords: ["uss", "at", "delhipublic", "library", "11kvess", "substation", "11kv"] },
  { label: 'USS at Lok Nayak Bhawan', value: '11kvess-uss-at-lok-nayak-bhawan', route: '/crew-management', keywords: ["uss", "at", "lok", "nayak", "bhawan", "11kvess", "substation", "11kv"] },
  { label: 'USS at Madrasi Camp Moti Bagh(W)', value: '11kvess-uss-at-madrasi-camp-moti-bagh-w', route: '/crew-management', keywords: ["uss", "at", "madrasi", "camp", "moti", "bagh", "w", "11kvess", "substation", "11kv"] },
  { label: 'USS at Mini Market Laxmi Bai Nagar', value: '11kvess-uss-at-mini-market-laxmi-bai-nagar', route: '/crew-management', keywords: ["uss", "at", "mini", "market", "laxmi", "bai", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'USS at Moti Bagh Barat Ghar', value: '11kvess-uss-at-moti-bagh-barat-ghar', route: '/crew-management', keywords: ["uss", "at", "moti", "bagh", "barat", "ghar", "11kvess", "substation", "11kv"] },
  { label: 'USS at Palika Maternuty Hospital Lodhi Colony', value: '11kvess-uss-at-palika-maternuty-hospital-lodhi-colony', route: '/crew-management', keywords: ["uss", "at", "palika", "maternuty", "hospital", "lodhi", "colony", "11kvess", "substation", "11kv"] },
  { label: 'USS at Palika Niwas', value: '11kvess-uss-at-palika-niwas', route: '/crew-management', keywords: ["uss", "at", "palika", "niwas", "11kvess", "substation", "11kv"] },
  { label: 'USS at XY Block Sarojni Nagar', value: '11kvess-uss-at-xy-block-sarojni-nagar', route: '/crew-management', keywords: ["uss", "at", "xy", "block", "sarojni", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'RMU at Jodhpur officer mess', value: '11kvess-rmu-at-jodhpur-officer-mess', route: '/crew-management', keywords: ["rmu", "at", "jodhpur", "officer", "mess", "11kvess", "substation", "11kv"] },
  { label: 'USS at YZ Block Sarojni Nagar', value: '11kvess-uss-at-yz-block-sarojni-nagar', route: '/crew-management', keywords: ["uss", "at", "yz", "block", "sarojni", "nagar", "11kvess", "substation", "11kv"] },
  { label: 'USS 44 Regal', value: '11kvess-uss-44-regal', route: '/crew-management', keywords: ["uss", "44", "regal", "11kvess", "substation", "11kv"] },
  { label: 'USS CNG Pump Scindia Road', value: '11kvess-uss-cng-pump-scindia-road', route: '/crew-management', keywords: ["uss", "cng", "pump", "scindia", "road", "11kvess", "substation", "11kv"] },
  { label: 'USS Competent House 3', value: '11kvess-uss-competent-house-3', route: '/crew-management', keywords: ["uss", "competent", "house", "3", "11kvess", "substation", "11kv"] },
  { label: 'USS Competent House 4', value: '11kvess-uss-competent-house-4', route: '/crew-management', keywords: ["uss", "competent", "house", "4", "11kvess", "substation", "11kv"] },
  { label: 'CSS Bombay Life1', value: '11kvess-css-bombay-life1', route: '/crew-management', keywords: ["css", "bombay", "life1", "11kvess", "substation", "11kv"] },
  { label: 'CSS Bombay Life2', value: '11kvess-css-bombay-life2', route: '/crew-management', keywords: ["css", "bombay", "life2", "11kvess", "substation", "11kv"] },
  { label: 'USS Gandhi Sadan', value: '11kvess-uss-gandhi-sadan', route: '/crew-management', keywords: ["uss", "gandhi", "sadan", "11kvess", "substation", "11kv"] },
  { label: 'USS Haldi ram', value: '11kvess-uss-haldi-ram', route: '/crew-management', keywords: ["uss", "haldi", "ram", "11kvess", "substation", "11kv"] },
  { label: 'USS Khandi Gram Udyog', value: '11kvess-uss-khandi-gram-udyog', route: '/crew-management', keywords: ["uss", "khandi", "gram", "udyog", "11kvess", "substation", "11kv"] },
  { label: 'USS Mandir Marg', value: '11kvess-uss-mandir-marg', route: '/crew-management', keywords: ["uss", "mandir", "marg", "11kvess", "substation", "11kv"] },
  { label: 'Marina Court Yard CSS 5', value: '11kvess-marina-court-yard-css-5', route: '/crew-management', keywords: ["marina", "court", "yard", "css", "5", "11kvess", "substation", "11kv"] },
  { label: 'USS Ranjeet Singh Flyover 1', value: '11kvess-uss-ranjeet-singh-flyover-1', route: '/crew-management', keywords: ["uss", "ranjeet", "singh", "flyover", "1", "11kvess", "substation", "11kv"] },
  { label: 'USS Ranjeet Singh Flyover 2', value: '11kvess-uss-ranjeet-singh-flyover-2', route: '/crew-management', keywords: ["uss", "ranjeet", "singh", "flyover", "2", "11kvess", "substation", "11kv"] },
  { label: 'USS Regal', value: '11kvess-uss-regal', route: '/crew-management', keywords: ["uss", "regal", "11kvess", "substation", "11kv"] },
  { label: 'USS Scindia House', value: '11kvess-uss-scindia-house', route: '/crew-management', keywords: ["uss", "scindia", "house", "11kvess", "substation", "11kv"] },
  { label: 'USS Sector 2 Gole Market', value: '11kvess-uss-sector-2-gole-market', route: '/crew-management', keywords: ["uss", "sector", "2", "gole", "market", "11kvess", "substation", "11kv"] },
  { label: 'USS Statee mporium', value: '11kvess-uss-statee-mporium', route: '/crew-management', keywords: ["uss", "statee", "mporium", "11kvess", "substation", "11kv"] },
  { label: 'USS 11 Ashoka Road', value: '11kvess-uss-11-ashoka-road', route: '/crew-management', keywords: ["uss", "11", "ashoka", "road", "11kvess", "substation", "11kv"] },
  { label: 'USS Iran Embassy', value: '11kvess-uss-iran-embassy', route: '/crew-management', keywords: ["uss", "iran", "embassy", "11kvess", "substation", "11kv"] },
  { label: 'USS Janpath Lane', value: '11kvess-uss-janpath-lane', route: '/crew-management', keywords: ["uss", "janpath", "lane", "11kvess", "substation", "11kv"] },
  { label: 'USS Lady Irvin College', value: '11kvess-uss-lady-irvin-college', route: '/crew-management', keywords: ["uss", "lady", "irvin", "college", "11kvess", "substation", "11kv"] },
  { label: 'USS Modern School', value: '11kvess-uss-modern-school', route: '/crew-management', keywords: ["uss", "modern", "school", "11kvess", "substation", "11kv"] },
  { label: '', value: '11kvess', route: '/crew-management', keywords: ["11kvess", "substation", "11kv"] },
  { label: 'USS 22 Tilak Marg', value: '11kvess-uss-22-tilak-marg', route: '/crew-management', keywords: ["uss", "22", "tilak", "marg", "11kvess", "substation", "11kv"] },
];


export {

   setPageColor,
   setDbNumberTrackColor,
   setDbNumberClass,
   setChartContainerClass,
   setHeaderTitleColor,
}